CONFIG_BSP_USING_SDIO=y
CONFIG_SD_MMC_DDR_SUPPORT=y
CONFIG_SD_MMC_OLINE_SUPPORT=y
CONFIG_BSP_USING_SDMMC1=y
CONFIG_SD_MAX_FREQ=48000000
CONFIG_CHERRYUSB_MSC_BACKEND_SDIO=y
CONFIG_CHERRYUSB_DEVICE_MSC_DEVNAME="sd0"
