Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = []
cwd = GetCurrentDir()
CPPPATH = [cwd]
libpath = [cwd]
libs = []
group = []

if GetDepend('PKG_USING_ANYKA') and not GetDepend('ANYKA_RUN_IN_ACPU'):
    libs = ['libakaudiofilter', 'm']
    group = DefineGroup('anyka', src, depend=['BF0_HCPU'], CPPPATH=CPPPATH, LIBS=libs, LIBPATH=libpath)

elif GetDepend('PKG_USING_ANYKA') and GetDepend('ANYKA_RUN_IN_ACPU'):
    src = Glob('*.c')
    libs = ['libakaudiofilter', 'm']
    group = DefineGroup('anyka', src, depend=['BF0_ACPU'], CPPPATH=CPPPATH, LIBS=libs, LIBPATH=libpath)

Return('group')
