from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]
lib = ['cortexM33_armcland-mdk531_common', 'cortexM33_armcland-mdk531_hba', 'cortexM33_armcland-mdk531_hrv', 'cortexM33_armcland-mdk531_nadt', 'cortexM33_armcland-mdk531_spo2']
group = DefineGroup('Drivers', src, depend = ['HR_USING_GH3018'], LIBS = lib, CPPPATH = path, LIBPATH = path)

Return('group')
