 [COMMON_SET]
PROTECT=0
JLINK_PATH=C:\Program Files (x86)\SEGGER\JLink
;1- use dll api  0- use jlink.exe
JLINK_CTRL=1
PORT_TYPE=1
PRODUCT_FLAG=1
FILEGROUP_FLAG=0
FUNC_TYPE=1
CALI_TYPE=1
ERASE_TYPE=1
TEST_TYPE=30
FROMNET_FLAG=1
ACCOUNT=
PASSWORD=
URLADDR=
URLADDR2=
WORKORDER=
FWVERIFY_FLAG=0
DELAY_SECOND=0
RETRY_LIMIT=1
RESET_BOOT=0
EZIP_FLAG=1
FACTORY_DB=1
MODE_TYPE=0

[CALI_SET]
CALI_VOLT=4000
CALI_VOLTRANGE=400
CALI_VOLTTHRESH=20
CALI_RESISTANCE_BIG=1000
CALI_RESISTANCE_SMALL=220
CALI_RESISTANCE_BIG_56x=1000
CALI_RESISTANCE_SMALL_56x=470
CALI_PORT_NUM=6
CALI_PORT=0
CALI_PORT_0=PB08
CALI_PORT_1=PB24
CALI_PORT_2=PB20
CALI_PORT_3=PB21
CALI_PORT_4=PB25
CALI_PORT_5=PB45
CALI_THRESHHOLD=5
CALI_TIMELEN=20
CALI_FREQIDX=3
CALI_CRYSTALTYPE=1
CALI_SYNCCODE=0x71764129
CALI_JUDGECNT=3
CALI_PKTSTEP=400
CALI_PKTINIT=200
CALI_PKTMAX=1600
;CALI_CBANK_MAX=0x3ff
;CALI_CBANK_MIN=0x10

[DEV_SET]
DEV_NUM=11
DEV_IDX=5
DEV_NAME0=SF32LB55X
DEV_NAME1=SF32LB55X_SD
DEV_NAME2=SF32LB56X
DEV_NAME3=SF32LB56X_NAND
DEV_NAME4=SF32LB56X_SD
DEV_NAME5=SF32LB52X
DEV_NAME6=SF32LB52X_NAND
DEV_NAME7=SF32LB52X_SD
DEV_NAME8=SF32LB58X_NAND
DEV_NAME9=SF32LB58X
DEV_NAME10=SF32LB58X_SD

[UART_DRIVER]
SF32LB55X=ram_patch.bin
SF32LB55X_SD=ram_patch_SD.bin
SF32LB56X=ram_patch_56X.bin
SF32LB56X_NAND=ram_patch_56X_NAND.bin
SF32LB56X_SD=ram_patch_56X_SD.bin
SF32LB52X=ram_patch_52X.bin
SF32LB52X_NAND=ram_patch_52X_NAND.bin
SF32LB52X_SD=ram_patch_52X_SD.bin
SF32LB58X_NAND=ram_patch_58X_NAND.bin
SF32LB58X=ram_patch_58X.bin
SF32LB58X_SD=ram_patch_58X_SD.bin

[UART_DRIVER_8M]
SF32LB56X_NAND=ram_patch_56X_NAND_8M.bin
SF32LB52X_NAND=ram_patch_52X_NAND_8M.bin
SF32LB58X_NAND=ram_patch_58X_NAND_8M.bin

[UART_COMPRESS]
SF32LB56X_NAND=1
SF32LB52X_NAND=1
SF32LB58X_NAND=1
SF32LB56X_SD=1
SF32LB52X_SD=1
SF32LB58X_SD=1

;FILE_SEARCH type
;1)nothing:  will not search in map file, use FILE_ADDR
;2)readfile:  will read the addr from the bin file
;3)muti>string1||string2:  will search muti string in map
;4)string:  will search string in map
;The first bin must select FTABLE
[FILE_SET]
PACK_PATH=
FACTORY_ADDR=0x1000E000
FILE_NUM=16

FILE_SEL_0=0
FILE_DES_0=FTABLE
FILE_NAME_0=ftab_qspi1_sec.bin||ftab.bin
FILE_ADDR_0=0x127b8000
FILE_SEARCH_0=readfile
;readfile will read the addr from the bin file
FILE_PATH_0=C:\Users\guichen\Downloads\v2.3.0.1_original\ROOT.bin

FILE_SEL_1=0
FILE_DES_1=OTA MANAGER
FILE_NAME_1=bf0_ap.bin||ota_manager.bin
FILE_ADDR_1=0x62060000
FILE_SEARCH_1=readfile
;readfile will read the addr from the bin file
FILE_PATH_1=C:\Users\guichen\Desktop\img_test\eh_lb525_nand_hdk\bootloader.bin

FILE_SEL_2=0
FILE_DES_2=APP
FILE_NAME_2=ER_IROM1.bin
FILE_ADDR_2=0x620e0000
FILE_SEARCH_2=muti>Load Region LR_IROM1 (Base:||Load Region LR_XIP_LRBIN (Base:
;muti Load Region LR_IROM1 (Base: or Load Region LR_IROM1 (Base:
FILE_PATH_2=C:\Users\guichen\Desktop\img_test\eh_lb525_nand_hdk\ER_IROM1.bin

FILE_SEL_3=1
FILE_DES_3=PIC
FILE_NAME_3=ER_IROM2.bin
FILE_ADDR_3=0x62080000
FILE_SEARCH_3=Load Region LR_IROM2 (Base:
FILE_PATH_3=C:\Users\guichen\Desktop\img_test\eh_lb525_nand_hdk\SYS.bin

FILE_SEL_4=1
FILE_DES_4=FONT
FILE_NAME_4=ER_IROM3.bin
FILE_ADDR_4=0x64080000
FILE_SEARCH_4=Load Region LR_IROM3 (Base:
FILE_PATH_4=C:\Users\guichen\Desktop\img_test\eh_563\ER_IROM1.bin

FILE_SEL_5=0
FILE_DES_5=TINY FONT
FILE_NAME_5=ER_IROM3_TINY.bin
FILE_ADDR_5=0x627a0000
FILE_SEARCH_5=Load Region LR_IROM3_TINY (Base:
FILE_PATH_5=C:\Users\guichen\Desktop\img_test\eh_lb525_nand_hdk\ROOT.bin

FILE_SEL_6=0
FILE_DES_6=OTA PIC
FILE_NAME_6=ER_IROM4.bin
FILE_ADDR_6=0x64a50000
FILE_SEARCH_6=Load Region LR_IROM4 (Base:
FILE_PATH_6=

FILE_SEL_7=1
FILE_DES_7=FS ROOT
FILE_NAME_7=root.bin
FILE_ADDR_7=0x64f00000
FILE_SEARCH_7=Load Region LR_FS_ROOT (Base:
FILE_PATH_7=C:\Users\guichen\Desktop\img_test\eh_lb525_nand_hdk\DYN.bin

FILE_SEL_8=0
FILE_DES_8=FS EX
FILE_NAME_8=ex.bin
FILE_ADDR_8=0x647c0000
FILE_SEARCH_8=Load Region LR_FS_EX (Base:
FILE_PATH_8=C:\Users\guichen\Desktop\img_test\eh_563\ROOT.bin

FILE_SEL_9=1
FILE_DES_9=FS SYS
FILE_NAME_9=sys.bin
FILE_ADDR_9=0x10380000
FILE_SEARCH_9=Load Region LR_NVM_SYS (Base:
FILE_PATH_9=D:\img\ec-lb551_v1.1_LB55SPI17801\sys.bin

FILE_SEL_10=0
FILE_DES_10=BOOT
FILE_NAME_10=bootloader.bin
FILE_ADDR_10=0x1C004000
FILE_SEARCH_10=readfile
FILE_PATH_10=C:\Users\guichen\Desktop\img_test\eh_563\lcpu_rom_patch.bin

FILE_SEL_11=0
FILE_DES_11=LCPU
FILE_NAME_11=lcpu_flash.bin
FILE_ADDR_11=0x64080000
FILE_SEARCH_11=
FILE_PATH_11=C:\Users\guichen\Desktop\img_test\eh_563\ER_IROM1.bin

FILE_SEL_12=1
FILE_DES_12=LCPU_PATCH
FILE_NAME_12=lcpu_rom_patch.bin
FILE_ADDR_12=0x64000000
FILE_SEARCH_12=
FILE_PATH_12=C:\Users\guichen\Desktop\img_test\eh_563\SYS.bin

FILE_SEL_13=0
FILE_DES_13=FONT
FILE_NAME_13=font.bin
FILE_ADDR_13=0x64000000
FILE_SEARCH_13=Load Region LR_FS_FONT (Base:
FILE_PATH_13=

FILE_SEL_14=0
FILE_DES_14=IMAGES
FILE_NAME_14=images.bin
FILE_ADDR_14=0x64300000
FILE_SEARCH_14=Load Region LR_FS_IMAGES (Base:
FILE_PATH_14=

FILE_SEL_15=0
FILE_DES_15=WATCH
FILE_NAME_15=watch.bin
FILE_ADDR_15=0x65300000
FILE_SEARCH_15=Load Region LR_FS_WATCHFACE (Base:
FILE_PATH_15=



[CHAN_SET]
CH1 =1
CH2 =1
CH3 =1
CH4 =1
CH5 =1
CH6 =1
CH7 =1
CH8 =1
CH9 =1
CH10=1
CH11=1
CH12=1
CH13=1
CH14=1
CH15=1
CH16=1

[UART_FILTER]
FILTER_FLAG=0
BAUND=3000000
VID =VID_0403
PID =PID_6011
CH1_DES =SIFLI_1_A
CH2_DES =SIFLI_1_B
CH3_DES =SIFLI_2_A
CH4_DES =SIFLI_2_B
CH5_DES =SIFLI_3_A
CH6_DES =SIFLI_3_B
CH7_DES =SIFLI_4_A
CH8_DES =SIFLI_4_B
CH9_DES =SIFLI_5_A
CH10_DES =SIFLI_5_B
CH11_DES =SIFLI_6_A
CH12_DES =SIFLI_6_B
CH13_DES =SIFLI_7_A
CH14_DES =SIFLI_7_B
CH15_DES =SIFLI_8_A
CH16_DES =SIFLI_8_B
CH1_PORT =COM29
CH2_PORT =COM9
CH3_PORT =COM10
CH4_PORT =COM11
CH5_PORT =COM12
CH6_PORT =COM13
CH7_PORT =COM14
CH8_PORT =COM15
CH9_PORT =COM16
CH10_PORT =COM17
CH11_PORT =COM18
CH12_PORT =COM19
CH13_PORT =COM20
CH14_PORT =COM21
CH15_PORT =COM22
CH16_PORT =COM23


[SWD_FILTER]
FILTER_FLAG=0
BAUND=5000
CH1_SN =69602837
CH2_SN =69604014
CH3_SN =69603847
CH4_SN =59604990
CH5_SN =941000024
CH6_SN =69604154
CH7_SN =69603848
CH8_SN =69604710
CH9_SN =69604029
CH10_SN =69604512
CH11_SN =69604358
CH12_SN =69603969
CH13_SN =69604398
CH14_SN =69604192
CH15_SN =69603999
CH16_SN =69604535

[LOG_SET]
GUI_FLAG =0
COMPARE_FLAG =0
VERIFY_FLAG=1
CHANEL_LOG=1
SCREEN_LOG=0
POST_ACT=0
PRE_ACT=1
GUIERR_FLAG=0
RETRY_NUM=0

[BLE_SET]
ENABLE_FLAG=1
RANDOM_FLAG=0
MASK_ADDR=FFFF
START_ADDR=C80000AB0000
END_ADDR=FFFFFFFFFFFF
CUR_ADDR=C80000AB0000
UP_VALUE=1
NAME_FLAG=0
BLE_NAME=sifli_test
BT_NAME_FLAG=0
BT_NAME=
LOCAL_FLAG=0
MAC_FLIE_FLAG=0
MAC_FILE=

[SN_SET]
ENABLE_FLAG=0
SN_DES=C140605A70024A01
START_VALUE=00000000
CUR_VALUE=00000013
UP_VALUE=1
OPPO_DES=
LOCAL_FLAG=0

[ALPAY_SET]
ENABLE_FLAG=0
PK=
DN=
DS=

[ALPAY_ERR]
NUM=0

[MACLOCAL_REUSE]
CHAN_2=
CHAN_1=
CHAN_3=
CHAN_4=
CHAN_5=
CHAN_6=
CHAN_7=
CHAN_8=
CHAN_9=
CHAN_10=
CHAN_11=
CHAN_12=
CHAN_13=
CHAN_14=
CHAN_15=
CHAN_16=

[SNLOCAL_REUSE]
CHAN_2=
CHAN_1=
CHAN_3=
CHAN_4=
CHAN_5=
CHAN_6=
CHAN_7=
CHAN_8=
CHAN_9=
CHAN_10=
CHAN_11=
CHAN_12=
CHAN_13=
CHAN_14=
CHAN_15=
CHAN_16=



[PRODUCT_INFO]
PROJECT_CODE=
CTEI_SUPPORT=1
