/*
 * SPDX-FileCopyrightText: 2019-2022 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "bsp_board.h"

void BSP_PIN_Init(void)
{
#ifdef SOC_BF0_HCPU
    // HCPU pins

    // codec ADC1
#ifdef ADC1_DIFFERENTIAL_INPUT
    HAL_PIN_Set_Analog(PAD_PA09, 1); // ADC1N
#endif
    HAL_PIN_Set_Analog(PAD_PA55, 1); // ADC1P
    HAL_PIN_Set_Analog(PAD_PA56, 1); // MICBIAS

    // SDIO1
#ifdef BSP_USING_SDMMC1
#if !defined(BSP_USING_BOARD_DPI_HDK_LB575YBBN6_E8_QSPI) && !defined(BSP_USING_BOARD_DPI_HDK_LB575YBBN6_S8_QSPI)
    /* single-line */
    HAL_PIN_Set(PAD_PA08, SD1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA09, SD1_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA10, SD1_DIO0, PIN_PULLUP, 1);
#else
    HAL_PIN_CompileTimeSet(PAD_PA14, SD1_CLK,  PIN_NOPULL, 1);
    HAL_PIN_CompileTimeSet(PAD_PA16, SD1_DIO0, PIN_PULLUP, 1);
    HAL_PIN_CompileTimeSet(PAD_PA17, SD1_DIO1, PIN_PULLUP, 1);
    HAL_PIN_CompileTimeSet(PAD_PA12, SD1_DIO2, PIN_PULLUP, 1);
    HAL_PIN_CompileTimeSet(PAD_PA13, SD1_DIO3, PIN_PULLUP, 1);
#endif /* !BSP_USING_BOARD_DPI_HDK_LB575YBBN6_E8_QSPI && !BSP_USING_BOARD_DPI_HDK_LB575YBBN6_S8_QSPI*/

#endif /* BSP_USING_SDMMC1 */

#ifdef BSP_USING_SDMMC2
    HAL_PIN_Set(PAD_PA02, SD2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA03, SD2_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA04, SD2_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA05, SD2_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA00, SD2_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA01, SD2_DIO3, PIN_PULLUP, 1);
#endif /* BSP_USING_SDMMC2 */


#if defined(BSP_USING_DCMI)
    // Digital Camera Interface

#ifdef BOARD_DVP_PINMAP_0
#ifdef USE_PTM_DVP_8WIRE
    HAL_PIN_Set(PAD_PA00, PTM1_CH10, PIN_NOPULL, 1); //VSYNC
    HAL_PIN_Set(PAD_PA01, PTM1_CH9, PIN_NOPULL, 1);  //HSYNC
    HAL_PIN_Set(PAD_PA03, PTM1_CH8, PIN_NOPULL, 1);  //CLK

    HAL_PIN_Set(PAD_PA04, PTM1_CH7, PIN_NOPULL, 1);  //D0
    HAL_PIN_Set(PAD_PA05, PTM1_CH4, PIN_NOPULL, 1);  //D3
    HAL_PIN_Set(PAD_PA07, PTM1_CH2, PIN_NOPULL, 1);  //D5  X  TP-RST
    HAL_PIN_Set(PAD_PA08, PTM1_CH6, PIN_NOPULL, 1);  //D1
    HAL_PIN_Set(PAD_PA09, PTM1_CH5, PIN_NOPULL, 1);  //D2  X  SDIO  R25
    HAL_PIN_Set(PAD_PA10, PTM1_CH3, PIN_NOPULL, 1);  //D4
    HAL_PIN_Set(PAD_PA35, PTM1_CH0, PIN_NOPULL, 1);  //D7  X  USB D+
    HAL_PIN_Set(PAD_PA36, PTM1_CH1, PIN_NOPULL, 1);  //D6
#else
    HAL_PIN_Set(PAD_PA00, DCMI_VSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA01, DCMI_HSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA03, DCMI_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA04, DCMI_DI0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA05, DCMI_DI3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA07, DCMI_DI5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA08, DCMI_DI1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA09, DCMI_DI2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA10, DCMI_DI4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA35, DCMI_DI7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA36, DCMI_DI6, PIN_NOPULL, 1);
#endif
    HAL_PIN_Set(PAD_PA02, GPTIM2_CH1, PIN_PULLUP, 1); // mclk output
#elif defined(BOARD_DVP_PINMAP_1)
    HAL_PIN_Set(PAD_PA26, DCMI_VSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA27, DCMI_HSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA29, DCMI_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA30, DCMI_DI0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA31, DCMI_DI3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA32, DCMI_DI1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA33, DCMI_DI2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA37, DCMI_DI7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA38, DCMI_DI6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA39, DCMI_DI5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA40, DCMI_DI4, PIN_NOPULL, 1);

    HAL_PIN_Set(PAD_PA28, GPTIM2_CH1, PIN_PULLUP, 1); // mclk output
#endif /* BOARD_DVP_PINMAP_0 */

#endif /* BSP_USING_DCMI */

#ifdef BSP_USING_PDM1
    HAL_PIN_Set(PAD_PA20, PDM1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA21, PDM1_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM1 */

#ifdef BSP_USING_PDM2
    HAL_PIN_Set(PAD_PA52, PDM2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA53, PDM2_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM2 */

#ifdef BOARD_TP_CAMERA_I2C_PINMAP_0
    HAL_PIN_Set(PAD_PA22, I2C1_SDA, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA23, I2C1_SCL, PIN_PULLUP, 1);
#elif BOARD_TP_CAMERA_I2C_PINMAP_1
    HAL_PIN_Set(PAD_PA51, I2C1_SDA, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA57, I2C1_SCL, PIN_PULLUP, 1);
#endif /* BOARD_TP_CAMERA_I2C_PINMAP_0 */

#endif  /* SOC_BF0_HCPU */


}

