Import('RTT_ROOT')
Import('rtconfig')
import os
import sys
from building import * 

cwd = GetCurrentDir()
src = []
path = [cwd]

if GetDepend('BSP_USING_MODEL_WATCH_GLOBAL_DATA'):
    src += Glob('watch_global_data.c')
if GetDepend('BSP_USING_MODEL_WATCH_SYS_INTERACT'):
    src += Glob('watch_system_interact.c')
if GetDepend('BSP_USING_UI_HANDLER'):
    src += Glob('ui_handler.c')
if GetDepend('BSP_USING_GESTURE_HANDLER'):
    src += Glob('gesture_handler.c')
if GetDepend('BSP_USING_VIRTUAL_CONSOLE'):
    src += Glob('virtual_console.c')
if GetDepend('BSP_USING_VIRTUAL_CONSOLE') and GetDepend('BSP_USING_WATCH_SYS_CLIENT'):
    src += Glob('hardware_selftest.c')
    path += [os.path.join(cwd, '..', 'bloc')]
if GetDepend('BSP_USING_TOUCH_STATE_MANAGER'):
    src += Glob('touch_state_manager.c')
if GetDepend('BSP_USING_AUDIO_PROCESSOR'):
    src += Glob('audio_code_i2s.c')
if GetDepend('BSP_USING_BLE_DEVICE_MANAGER'):
    src += Glob('ble_device_manager.c')
if GetDepend('BSP_USING_BLE_HID'):
    src += Glob('ble_hid.c')
if GetDepend('BSP_USING_BLE_LOG'):
    src += Glob('ble_ulog_backend.c')

group = DefineGroup('Model', src, depend = [''], CPPPATH = path)

Return('group')
