Import('RTT_ROOT')
Import('rtconfig')
import os
import sys
from building import * 

cwd = GetCurrentDir()
src = []
path = [cwd]

if GetDepend('BSP_USING_MODEL_WATCH_GLOBAL_DATA'):
    src += Glob('watch_global_data.c')
if GetDepend('BSP_USING_MODEL_WATCH_SYS_INTERACT'):
    src += Glob('watch_system_interact.c')
    src += Glob('watch_system_core_task.c')
if GetDepend('BSP_USING_UI_HANDLER'):
    src += Glob('ui_handler.c')
if GetDepend('BSP_USING_GESTURE_HANDLER'):
    src += Glob('gesture_handler.c')
if GetDepend('BSP_USING_VIRTUAL_CONSOLE'):
    src += Glob('virtual_console.c')
if GetDepend('BSP_USING_TOUCH_STATE_MANAGER'):
    src += Glob('touch_state_manager.c')
    
group = DefineGroup('Model', src, depend = [''], CPPPATH = path)

Return('group')
