Import('RTT_ROOT')
Import('rtconfig')
import os
import sys
from building import * 

cwd = GetCurrentDir()

src = []
path = [cwd]
src = Glob('*.cc') + Glob('*.c')

group = DefineGroup('GestureRecognition', src, depend = ['BSP_USING_GESTURE_RECOGNITION'], CPPPATH = path)

Return('group')
