/*Auto generated configuration*/
#ifndef RT_CONFIG_H
#define RT_CONFIG_H

#define SOC_SF32LB57X 1
#define SOC_SF32LB57X_GENERIC 1
#define CORE "HCPU"
#define CPU "Cortex-M33"
#define BSP_USING_BOARD_SF32LB57_RAMRUN 1
#define LXT_FREQ 32768
#define LXT_LP_CYCLE 200
#define BLE_TX_POWER_VAL 0
#define LCPU_CONFIG_AUTO 1
#define ASIC 1
#define EZIP_PAL_SUPPORT 1
#define EZIP_PAL_SUPPORT_1 1
#define CONSOLE_UART1 1
#define RT_CONSOLE_DEVICE_NAME "uart1"
#define SD_INSERT_DETECT_PIN -1
#define BSP_USING_NO_OS 1
#define BSP_USING_EMPTY_ASSERT 1
#define ROM_ATT_BUF_SIZE 3084
#define ROM_LOG_SIZE 4096
#define LCPU_RUN_ROM_COMBINE_RAM 1
#define BT_DUAL_HOST_MEM 1
#define MB_PORT 1
#define UART_PORT1 1
#define UART_PORT1_PORT "uart4"
#define IPC_USE_CONSOLE_DEVICE 1
#define USING_SF_CRYPTO 1
#define SF_CRYPTO_PORT_BAREMETAL 1
#define USING_PARTITION_TABLE 1
#define PKG_SIFLI_MBEDTLS_BOOT 1
#define BF0_HCPU 1
#define CFG_BOOTLOADER 1
#define CUSTOM_MEM_MAP 1
#endif
