/*Auto generated configuration*/
#ifndef RT_CONFIG_H
#define RT_CONFIG_H

#define SOC_SF32LB57X 1
#define CORE "HCPU"
#define CPU "Cortex-M33"
#define BSP_NO_BOARD_USED 1
#define LXT_FREQ 32768
#define LXT_LP_CYCLE 200
#define BLE_TX_POWER_VAL 0
#define LCPU_CONFIG_AUTO 1
#define EZIP_PAL_SUPPORT 1
#define EZIP_PAL_SUPPORT_1 1
#define BSP_USING_NO_OS 1
#define BSP_USING_EMPTY_ASSERT 1
#define ROM_ATT_BUF_SIZE 3084
#define ROM_LOG_SIZE 4096
#define LCPU_RUN_ROM_COMBINE_RAM 1
#define IPC_USE_CONSOLE_DEVICE 1
#define USING_SF_CRYPTO 1
#define SF_CRYPTO_PORT_BAREMETAL 1
#define PKG_SIFLI_MBEDTLS_BOOT 1
#define PKG_USING_CHERRYUSB 1
#define PKG_CHERRYUSB_DEVICE 1
#define PKG_CHERRYUSB_DEVICE_SPEED_FS 1
#define PKG_CHERRYUSB_DEVICE_MUSB_SIFLI 1
#define PKG_CHERRYUSB_DEVICE_CDC_ACM 1
#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 512
#define CONFIG_USBDEV_MSC_MAX_BUFSIZE 512
#define PKG_CHERRYUSB_DEVICE_TEMPLATE_NONE 1
#define PKG_CHERRYUSB_PATH "/packages/system/CherryUSB"
#define PKG_USING_CHERRYUSB_V010502 1
#define PKG_CHERRYUSB_VER "v1.5.2"
#define BF0_HCPU 1
#define CFG_BOOTLOADER 1
#define CFG_BOOTROM 1
#define SD_BOOT 1
#endif
