/*
 * SPDX-FileCopyrightText: 2019-2025 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __GUI_APP_FWK_H__
#define __GUI_APP_FWK_H__

#include <rtthread.h>
#include <rtdevice.h>
#include <board.h>
#include <string.h>

#include "lvgl.h"

#include "intent.h"

/**
 ****************************************************************************************
* @addtogroup gui_app_fwk GUI Application Framework
* @ingroup middleware
* @brief Sifli GUI application framework, provide basic functions for user to start/stop/pause/resume
*  application. It also provide navigation among applications and transition of GUI.
* @{
****************************************************************************************
*/


#ifdef __cplusplus
extern "C" {
#endif

#define GUI_APP_NAME_MAX_LEN            16  //!< App display name max length
#define GUI_APP_ID_MAX_LEN              16  //!< An unique character id of an app (both bult-in app and dl app)
#define GUI_DL_APP_MAX_FILE_PATH_LEN    64  //!< Max file path length for dynamic loading applications
#if defined(_MSC_VER)
#define MSC_APP_STRUCT_MAGIC_HEAD 0xAB
#endif


typedef int (*gui_app_entry_func_ptr_t)(intent_t i);
typedef int16_t gui_anim_value_t;
typedef lv_obj_t *gui_anim_obj_t;
typedef int16_t gui_coord_t;
typedef struct
{
    gui_coord_t x;
    gui_coord_t y;
} gui_point_t;

/**
   application types
 */
typedef enum
{
    /**
        built-in applications.
    */
    GUI_APP_BUILTIN = 0,

    /**
        Dynamic applications.
    */
    GUI_APP_DYNAMIC,

    /**
        Applications written by QuickJS.
    */
    GUI_APP_QJS,

    /**
        Applications written by python.
    */
    GUI_APP_PYTHON,

    /**
        Applications generated by tools.
    */
    GUI_APP_TOOLS,

    /**
        Reserved, user-defined.
    */
    GUI_APP_RESERVE,

} gui_app_type_t;

/**
   built-in app description
 */
typedef struct
{
#if defined(_MSC_VER)
    uint8_t  magic_flag;  //!< Maigc struct header for simulator
#endif

#ifdef LV_USING_EXT_RESOURCE_MANAGER
    uint32_t name;   //!< app display name string id
#else
    char name[GUI_APP_NAME_MAX_LEN];   //!< app display name
#endif
    const void *icon;                  //!< app display icon
    char id[GUI_APP_ID_MAX_LEN];       //!< an unique character id of an app (both bult-in app and dl app)
    gui_app_entry_func_ptr_t entry;    //!< app entry function
    gui_app_type_t type;               //!< app types

} builtin_app_desc_t;


/**
    Define a build-in GUI applications:
    name - name which will display on mainmenu
    icon - icon which will display on mainmenu too.
    id   - let other app find this app by id
    entry- app's entry function
    n    - group id/sytle id
*/
#define BUILTIN_APP_EXPORT(name, icon, id, entry, n)                            \
    SECTION_ITEM_REGISTER(BuiltinApp##n##Tab, RT_USED static const builtin_app_desc_t CONCAT_2(__builtinapp, n)) =  \
    {                                                                           \
        name,                                                                   \
        icon,                                                                   \
        id,                                                                     \
        (gui_app_entry_func_ptr_t)entry,                                        \
        GUI_APP_BUILTIN                                                         \
    }


#include "gui_app_fwk2.h"


typedef void (*gui_page_msg_cb_t)(gui_app_msg_type_t msg, void *param);

/**
    @brief register an application's root page message handler
    @param[in] id Identification of application
    @param[in] handler The main subpage message handler.
    @param[in] usr_data User data of this app
    @retval RT_EOK if successful, otherwise return error number < 0.
 */
int gui_app_regist_msg_handler_ext(const char *id, gui_page_msg_cb_t handler, void *usr_data, uint32_t mem_size);
#define gui_app_regist_msg_handler(id,handler) gui_app_regist_msg_handler_ext(id,handler, NULL, 0)

/**
    @brief Create a subgpage in current actived app, and present it.
    @param[in] pg_id Subpage id (should be unique in one app )
    @param[in] handler This subpage message handler
    @param[in] usr_data User data of this subpage
    @retval RT_EOK if successful, otherwise return error number < 0.
 */
int gui_app_create_page_ext(const char *pg_id, gui_page_msg_cb_t handler, void *usr_data);
#define gui_app_create_page(pg_id,pg_handler) gui_app_create_page_ext(pg_id, pg_handler, NULL)

/**
    @brief Create a subgpage for specified app, and present it.
    @param[in] app_id Identification of an application
    @param[in] pg_id Subpage id (should be unique in one app )
    @param[in] handler This subpage message handler
    @param[in] usr_data User data of this subpage
    @retval RT_EOK if successful, otherwise return error number < 0.
 */
int gui_app_create_page_for_app_ext(const char *app_id, const char *pg_id,
                                    gui_page_msg_cb_t handler, void *user_data, uint32_t mem_size);
#define gui_app_create_page_for_app(app_id,pg_id,pg_handler) gui_app_create_page_for_app_ext(app_id,pg_id,pg_handler,NULL, 0)

/************************ Application transfer animation *******************************************************/
#include "lvsf_switchanim.h"

#define GUI_APP_TRANS_PROGRESS_MAX 1024

typedef  lv_baseanim_para_t gui_app_trans_anim_t ;

void gui_app_set_finsh_cb(lv_switchanim_finish_cb cb);

void gui_app_init_anim(gui_app_trans_anim_t *anim);

void gui_app_set_anim_prior(int16_t enter_prior, int16_t exit_prior);

void gui_app_set_anim_user_data(void *enter_user, void *exit_user);

void gui_app_set_enter_anim_type(uint16_t major, uint16_t minor, int16_t minor_aux);

void gui_app_set_exit_anim_type(uint16_t major, uint16_t minor, int16_t minor_aux);

void gui_app_close_anim();

rt_err_t gui_app_manual_animation_start(uint32_t process);

rt_err_t gui_app_manual_animation_update(uint32_t process);

rt_err_t gui_app_manual_animation_stop(uint32_t process);

extern const builtin_app_desc_t *gui_builtin_app_list_open(void);

extern const builtin_app_desc_t *gui_builtin_app_list_get_next(const builtin_app_desc_t *ptr_app);

enum
{
    SCRIPT_TYPE_QJS,
    SCRIPT_TYPE_MPY,
    SCRIPT_TYPE_NUM,
};
typedef uint8_t gui_script_type_t;

/**
    @brief Get script app(js/mpy) desc, this func will malloc memory internal, must release memory when desc is not used.
    @param[in] desc NULL for get first app, -1 for close internal fd.
    @param[in] type script type, see gui_script_type_t.
    @retval NULL if get end, otherwise return success.
 */
const builtin_app_desc_t *gui_script_app_list_get_next(const builtin_app_desc_t *desc, gui_script_type_t type);

/**
    @brief Free script desc.
    @param[in] desc for free.
    @param[in] icon_release true for release, false for ignore.
    @param[in] type script type, see gui_script_type_t.
    @retval None.
 */
void gui_script_app_list_free_desc(const builtin_app_desc_t *app, bool icon_release, gui_script_type_t type);

void gui_script_watch_face_register(gui_script_type_t type);



extern void gui_builtin_app_list_close(const builtin_app_desc_t *ptr_app);

#ifdef PKG_USING_MICROPYTHON
extern void pyapp_msg_handler(gui_app_msg_type_t msg, void *param);
#endif

/// @}  gui_app_fwk

#ifdef __cplusplus
}
#endif
#endif  /* __GUI_APP_FWK_H__ */
