from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB55_LCD_N16R4N4'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB55_LCD_N16R4N4'):
    group = group + SConscript(os.path.join(cwd, '../sf32lb55-lcd_base/script/SConscript'))

Return('group')
