import os
import rtconfig

# Check SDK 
SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print("Please run set_env.bat in root folder of SIFLI SDK to set environment.")
    exit()
from building import *

PrepareEnv()
################################## change rtconfig.xxx to customize build ########################################
# print (rtconfig.OUTPUT_DIR)

# Add bootloader project
AddBootLoader(SIFLI_SDK,rtconfig.CHIP)

SifliEnv()
if rtconfig.CHIP == 'SF32LB55X' and GetConfigValue('BSP_LB55X_CHIP_ID') < 3:
    import shutil
    shutil.copy(os.path.join(SIFLI_SDK, 'example/rom_bin/lcpu_general_ble_img/lcpu_lb555.c'),
                os.path.normpath(os.path.join(SIFLI_SDK, 'example/ble/multi_connection/src/lcpu_img.c')))
else:
    AddLCPU(SIFLI_SDK,rtconfig.CHIP, "../../src/lcpu_img.c")

TARGET = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT

# prepare building environment
objs = PrepareBuilding(None)
env = GetCurrentEnv()

# make a building
DoBuilding(TARGET, objs)

# Add flash table
AddFTAB(SIFLI_SDK,rtconfig.CHIP)

GenDownloadScript(env)
