from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_FPGA_57X_MEM_V3_MPI2'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_FPGA_57X_MEM_V3_MPI2'):
    group = group + SConscript('../fpga-57x_base/SConscript.base')

Return('group')
