Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

if GetDepend('PKG_USING_3MICS'):
    src = []
elif GetDepend('PKG_USING_SOUNDPLUS'):
    src = Glob('audio_3a_soundplus.c')
elif GetDepend('PKG_USING_ANYKA'):
    src = Glob('audio_3a_anyka.c')
elif GetDepend('PKG_USING_WEBRTC'):
    src = Glob('audio_3a.c')
else:
    src = Glob('./audio_3a_dummy.c')

if GetDepend('AUDIO_FREQSHIFT'):
    src += ['audio_freqshift.c']

if GetDepend('AUDIO_SOFTEQ'):
    src += ['audio_softeq.c']
    
group = DefineGroup('audio', src,depend = [''],CPPPATH = CPPPATH)

Return('group')
