import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
bf0_ap_hal_msp.c
main.c
''')

if GetDepend('SD_BL_MODE'):
    src += ['sd_emmc_drv.c', 'sd_emmc_ops.c']

path =  [cwd]
path += [cwd + '/ports']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')
