CONFIG_BSP_USING_SPI=y
CONFIG_BSP_USING_SPI1=y
CONFIG_BSP_SPI1_TX_USING_DMA=y
CONFIG_BSP_SPI1_RX_USING_DMA=y
CONFIG_RT_USING_SPI_MSD=y
# CONFIG_RT_DFS_ELM_DHARA_ENABLED is not set
CONFIG_RT_USING_MTD_DHARA=y
CONFIG_EZIP_SDCARD_BACKEND_SPI_MSD=y
CONFIG_EZIP_SDCARD_DEVNAME="sd0"
