from building import *

Import('rtconfig')

src   = Glob('*.c')
if GetDepend('BSP_USING_PC_SIMULATOR'):
    SrcRemove(src,['unistd.c'])
cwd   = GetCurrentDir()
group = []
CPPPATH = [cwd+'/include']

group = DefineGroup('libc', src, depend = ['RT_USING_LIBC'], CPPPATH = CPPPATH)

Return('group')
