/*
 * SPDX-FileCopyrightText: 2019-2022 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "bsp_board.h"

void BSP_PIN_Init(void)
{
#ifdef SOC_BF0_HCPU
    // HCPU pins

    // MPI3
#ifdef SOC_SF32LB573UB776
    HAL_PIN_Set(PAD_SB09, MPI3_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_SB03, MPI3_CS,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_SB07, MPI3_DIO0, PIN_PULLDOWN, 1);
    HAL_PIN_Set(PAD_SB02, MPI3_DIO1, PIN_PULLDOWN, 1);
    HAL_PIN_Set(PAD_SB01, MPI3_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_SB08, MPI3_DIO3, PIN_PULLUP, 1);
#endif /* SOC_SF32LB573UB776 */

    // SDIO1
#ifdef BSP_USING_SDMMC1
#ifdef BOOT_DEVICE_SDMMC1
    HAL_PIN_Set(PAD_PA14, SD1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA15, SD1_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA16, SD1_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA17, SD1_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA12, SD1_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA13, SD1_DIO3, PIN_PULLUP, 1);
#else
    HAL_PIN_Set(PAD_PA24, SD1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA25, SD1_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA26, SD1_DIO0, PIN_PULLUP, 1);
#endif /* BOOT_DEVICE_SDMMC1 */
#endif /* BSP_USING_SDMMC1 */

#ifdef BSP_USING_SDMMC2
    //TODO
    HAL_PIN_Set(PAD_PA30, SD2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA31, SD2_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA32, SD2_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA33, SD2_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA28, SD2_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA29, SD2_DIO3, PIN_PULLUP, 1);
#endif

#ifdef BSP_LCDC_USING_QADSPI
    HAL_PIN_Set(PAD_PA04, LCDC1_SPI_CLK, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA03, LCDC1_SPI_CS, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA05, LCDC1_SPI_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA06, LCDC1_SPI_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA07, LCDC1_SPI_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA08, LCDC1_SPI_DIO3, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA02, LCDC1_SPI_TE, PIN_PULLUP, 1);
#endif /* BSP_LCDC_USING_QADSPI */

    // TP I2C1
    HAL_PIN_Set(PAD_PA20, I2C1_SDA, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA27, I2C1_SCL, PIN_PULLUP, 1);

#if defined(BSP_USING_DCMI)
    // Digital Camera Interface
    HAL_PIN_Set(PAD_PA39, GPTIM2_CH1, PIN_PULLUP, 1); // mclk output

    HAL_PIN_Set(PAD_PA40, DCMI_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA37, DCMI_VSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA38, DCMI_HSYNC, PIN_NOPULL, 1);

#if 1
// TODO: 4-line
    HAL_PIN_Set(PAD_PA41, DCMI_DI0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA43, DCMI_DI1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, DCMI_DI2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA42, DCMI_DI3, PIN_NOPULL, 1);
#else
// TODO: 8-line
    HAL_PIN_Set(PAD_PA41, DCMI_DI0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA43, DCMI_DI1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, DCMI_DI2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA42, DCMI_DI3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA48, DCMI_DI4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA47, DCMI_DI5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA46, DCMI_DI6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA45, DCMI_DI7, PIN_NOPULL, 1);
#endif

#endif

#ifdef SOC_PACKAGE_QFN68

#ifdef BOARD_PDM_PINMAP_0
#ifdef BSP_USING_PDM1
    HAL_PIN_Set(PAD_PA41, PDM1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA42, PDM1_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM1 */
#ifdef BSP_USING_PDM2
    HAL_PIN_Set(PAD_PA43, PDM2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, PDM2_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM2 */
#elif defined(BOARD_PDM_PINMAP_1)
#ifdef BSP_USING_PDM1
    HAL_PIN_Set(PAD_PA05, PDM1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA06, PDM1_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM1 */
#ifdef BSP_USING_PDM2
    HAL_PIN_Set(PAD_PA07, PDM2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA08, PDM2_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM2 */
#endif /* BOARD_PDM_PINMAP_0 */

#elif defined(SOC_PACKAGE_QFN80)

#ifdef BSP_USING_PDM1
    HAL_PIN_Set(PAD_PA49, PDM1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA50, PDM1_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM1 */
#ifdef BSP_USING_PDM2
    HAL_PIN_Set(PAD_PA52, PDM2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA53, PDM2_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM2 */

#endif /* SOC_PACKAGE_QFN68 */

#endif  /* SOC_BF0_HCPU */


}

