import os
from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = [cwd]
inc = inc + [os.path.join(cwd, '..')]


# Only build the multilingual/resource-manager implementation when the
# feature is enabled. The public headers already provide fallback macros for
# projects that do not select LV_USING_EXT_RESOURCE_MANAGER.
if GetDepend('LV_USING_EXT_RESOURCE_MANAGER'):
    src = src + Glob('./*.c')

# add group to IDE project
objs = DefineGroup('lv_ext_resouce', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc)
Return('objs')
