CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_OUTPUT_THREAD_NAME=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_BLUETOOTH=y
# CONFIG_BLE_CTKD_ENABLE is not set
CONFIG_BSP_BLE_LOG=y
CONFIG_BSP_BLE_SERIAL_TRANSMISSION=y
CONFIG_USING_COREDUMP=y
CONFIG_USING_BUTTON_LIB=y
CONFIG_PKG_USING_FLASHDB=y
