CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_USING_ULOG=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_USING_CPU_USAGE_PROFILER=y
CONFIG_CPU_USAGE_METRICS_ENABLED=y
CONFIG_CPU_USAGE_METRICS_PRINT_DIRECTLY=y
CONFIG_AUDIO=y
CONFIG_AUDIO_LOCAL_MUSIC=y
CONFIG_USING_ELM_RW=y
CONFIG_PKG_LIB_FLAC=y
CONFIG_STARTUP_STACK_SIZE=10000
