from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SPI_HDK_LB575YBBN6_N16'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SPI_HDK_LB575YBBN6_N16'):
    group = group + SConscript('../sf32lb57-spi-hdk_base/SConscript.base')

Return('group')
