/**
 ******************************************************************************
 * @file   ui_img_helper.h
 * @author Skaiwalk software development team
 ******************************************************************************
 */
// #include "ui_img_helper.h"
#ifndef UI_IMG_HELPER_H
#define UI_IMG_HELPER_H

#define BTN_FLASHLIGHT "/assets/icons/btn_flashlight.bin"
#define BG_LODING "/assets/icons/bg_loading.bin"
#define IMG_FLASHLIGHT "/assets/icons/img_flashlight.bin"
#define IMG_ACTIVITY "/assets/icons/img_activity.bin"
#define IMG_ALARM_2 "/assets/icons/img_alarm_2.bin"
#define IMG_CALENDAR "/assets/icons/img_calendar.bin"
#define IMG_GAME "/assets/icons/img_game.bin"
#define IMG_GROUP "/assets/icons/img_group.bin"
#define IMG_PHOTO "/assets/icons/img_photo.bin"
#define IMG_RECORDER "/assets/icons/img_recorder.bin"
#define IMG_LOGO "/assets/icons/img_logo.bin"
#define IMG_NOTE "/assets/icons/img_note.bin"
#define IMG_WORKOUT "/assets/icons/img_workout.bin"
#define IMG_ITUNES "/assets/icons/img_itunes.bin"
#define IMG_HEART_RATE "/assets/icons/img_heart_rate.bin"
#define IMG_CALCULATOR "/assets/icons/img_calculator.bin"
#define IMG_ALARM "/assets/icons/img_alarm.bin"
#define IMG_SETTINGS "/assets/icons/img_settings.bin"
#define IMG_MESSAGES "/assets/icons/img_messages.bin"
#define IMG_MOUSE "/assets/icons/img_mouse.bin"
#define SMALL_IMG_LOGO_MATTING "/assets/icons/small_img_logo_matting.bin"
#define UP_ARROW "/assets/icons/up_arrow.bin"
#define DOWN_ARROW "/assets/icons/down_arrow.bin"
#define PREVIOUS_ARROW "/assets/icons/previous_arrow.bin"
#define NEXT_ARROW "/assets/icons/next_arrow.bin"
#define ICON_APPLE_FACETIME "/assets/icons/icon_apple_facetime.bin"
#define ICON_GOOGLE_CALENDAR "/assets/icons/icon_google_calendar.bin"
#define ICON_FACEBOOK "/assets/icons/icon_facebook.bin"
#define ICON_INSTAGRAM "/assets/icons/icon_instagram.bin"
#define ICON_KAKAOTALK "/assets/icons/icon_kakaotalk.bin"
#define ICON_LINE "/assets/icons/icon_line.bin"
#define ICON_LINKEDIN "/assets/icons/icon_linkedin.bin"
#define ICON_APPLE_MAIL "/assets/icons/icon_apple_mail.bin"
#define ICON_MESSENGER "/assets/icons/icon_messenger.bin"
#define ICON_OTHER "/assets/icons/icon_other.bin"
#define ICON_QQ "/assets/icons/icon_qq.bin"
#define ICON_SKYPE "/assets/icons/icon_skype.bin"
#define ICON_SMS "/assets/icons/icon_sms.bin"
#define ICON_SNAP "/assets/icons/icon_snap.bin"
#define ICON_TWITTER "/assets/icons/icon_twitter.bin"
#define ICON_WECHAT "/assets/icons/icon_wechat.bin"
#define ICON_WHATSAPP "/assets/icons/icon_whatsapp.bin"
#define ICON_GMAIL "/assets/icons/icon_gmail.bin"
#define ICON_DINGTALK "/assets/icons/icon_dingtalk.bin"
#define ICON_GOOGLE_CHAT "/assets/icons/icon_google_chat.bin"
#define ICON_DISCORD "/assets/icons/icon_discord.bin"
#define ICON_YOUTUBE "/assets/icons/icon_youtube.bin"
#define ICON_PROHIBIT "/assets/icons/icon_prohibit.bin"
#define ICON_SAND "/assets/icons/icon_send.bin"
#define ICON_TRASH "/assets/icons/icon_trash.bin"
#define SKAIWALKICON "/assets/icons/skaiwalkicon.bin"
#define IMG_CHARGING "/assets/icons/img_charging.bin"
#define ICON_DELETE "/assets/icons/icon_delete.bin"
#define APP_ELC_5 "/assets/icons/app_elc_5.bin"
#define APP_ELC_20 "/assets/icons/app_elc_20.bin"
#define APP_ELC_40 "/assets/icons/app_elc_40.bin"
#define APP_ELC_60 "/assets/icons/app_elc_60.bin"
#define APP_ELC_80 "/assets/icons/app_elc_80.bin"
#define APP_ELC_100 "/assets/icons/app_elc_100.bin"
#define IMG_LOW_POWER "/assets/icons/img_low_power.bin"
#define ICON_BLUETOOTH_DISCONNECTION "/assets/icons/icon_bluetooth_disconnection.bin"
#define CHARGE_ICON "/assets/icons/charge_icon.bin"
#define ICON_X "/assets/icons/icon_x.bin"
#define CALCULATOR_ICON "/assets/icons/calculator_icon.bin"
#define FIND_PHONE "/assets/icons/find_phone.bin"
#define FLISHLIGHT_ICON "/assets/icons/flashlight_icon.bin"
#define IMG_MAIL "/assets/icons/img_mail.bin"

// #define GAUS_DEFAULT_PICTURE "/assets/gaus_images/gaus_default_picture.bin"
extern char *GAUS_DEFAULT_PICTURE;
#define GAUS_CLOCK5_BG "/assets/gaus_images/gaus_clock5_bg.bin"
#define GAUS_CLOCK4_BG "/assets/gaus_images/gaus_clock4_bg.bin"
#define GAUS_CLOCK1_BG "/assets/gaus_images/gaus_clock1_bg.bin"

#define MEDIA_MASK "/assets/images/media_mask.bin"
extern char MEDIA_IMG[40];
#endif

/************************ (C) COPYRIGHT Skaiwalk Technology *******END OF FILE****/