from building import *
import os
import SConstruct
import rtconfig

PrepareEnv()

SConstruct.create_env()
SConstruct.build()

SIFLI_SDK = os.getenv('SIFLI_SDK')

AddFTAB(SIFLI_SDK, rtconfig.CHIP)

env = GetCurrentEnv()
GenDownloadScript(env)

