/* 英文常用字表(字母序,小寫;founder 2026-07-22 英文選字推薦)。
   prefix 掃描用;約 560 常用詞。 */
#include "en_words.h"

const char *const g_en_words[] = {
    "about", "above", "accept", "access", "account", "across", "action",
    "active", "actually", "address", "after", "again", "against", "agree",
    "airport", "album", "all", "allow", "almost", "alone", "along", "already",
    "also", "always", "amazing", "amount", "and", "another", "answer", "any",
    "anyone", "anything", "app", "apple", "apply", "area", "around", "arrive",
    "article", "ask", "attach", "audio", "auto", "available", "awesome",
    "baby", "back", "bad", "bank", "battery", "beach", "beautiful", "because",
    "become", "been", "before", "begin", "behind", "believe", "best", "better",
    "between", "big", "bill", "birthday", "bit", "black", "block", "blue",
    "board", "body", "book", "boss", "both", "bottom", "box", "break",
    "breakfast", "bring", "brother", "browser", "budget", "build", "business",
    "busy", "button", "buy", "cable", "calendar", "call", "camera", "can",
    "cancel", "cannot", "car", "card", "care", "case", "cash", "catch",
    "center", "chance", "change", "channel", "charge", "chat", "check",
    "child", "choose", "city", "class", "clean", "clear", "click", "client",
    "clock", "close", "cloud", "code", "coffee", "cold", "come", "comment",
    "company", "complete", "computer", "confirm", "connect", "contact",
    "content", "control", "cook", "cool", "copy", "correct", "cost", "could",
    "country", "course", "cover", "create", "credit", "current", "customer",
    "cut", "daily", "damage", "dark", "data", "date", "day", "deal", "dear",
    "debug", "decide", "deep", "delete", "deliver", "design", "desktop",
    "detail", "device", "did", "different", "difficult", "dinner", "direct",
    "discuss", "display", "document", "does", "doing", "done", "door",
    "double", "down", "download", "draft", "drink", "drive", "driver", "drop",
    "during", "each", "early", "easy", "eat", "edit", "either", "else",
    "email", "empty", "end", "energy", "engine", "english", "enjoy", "enough",
    "enter", "error", "even", "evening", "event", "ever", "every", "everyone",
    "everything", "exactly", "example", "excellent", "except", "exchange",
    "excuse", "exercise", "exit", "expect", "export", "extra", "face", "fact",
    "fail", "fall", "family", "fast", "father", "favorite", "feature", "feel",
    "few", "field", "file", "fill", "film", "final", "find", "fine", "finish",
    "first", "fix", "flight", "focus", "folder", "follow", "food", "for",
    "forget", "form", "forward", "found", "free", "friend", "from", "front",
    "full", "function", "funny", "future", "game", "garden", "general", "get",
    "gift", "girl", "give", "glad", "glass", "goal", "going", "good", "google",
    "great", "green", "group", "grow", "guess", "guide", "had", "hand",
    "handle", "happen", "happy", "hard", "has", "have", "head", "health",
    "hear", "heart", "heavy", "hello", "help", "here", "high", "history",
    "hold", "home", "hope", "hospital", "hot", "hotel", "hour", "house",
    "how", "however", "human", "hungry", "idea", "image", "import",
    "important", "inside", "install", "instead", "interest", "internet",
    "into", "invite", "issue", "item", "job", "join", "just", "keep", "key",
    "keyboard", "kind", "know", "language", "laptop", "large", "last", "late",
    "later", "launch", "learn", "leave", "left", "less", "lesson", "let",
    "letter", "level", "life", "light", "like", "line", "link", "list",
    "listen", "little", "live", "local", "location", "lock", "login", "long",
    "look", "love", "lunch", "machine", "made", "mail", "main", "make",
    "manage", "manager", "many", "map", "market", "match", "matter", "may",
    "maybe", "mean", "media", "meet", "meeting", "member", "memory", "menu",
    "message", "method", "middle", "might", "mind", "mine", "minute", "miss",
    "mobile", "mode", "model", "moment", "money", "month", "more", "morning",
    "most", "mother", "mouse", "move", "movie", "much", "music", "must",
    "name", "near", "need", "network", "never", "new", "news", "next", "nice",
    "night", "normal", "not", "note", "nothing", "notice", "now", "number",
    "offer", "office", "often", "okay", "old", "once", "online", "only",
    "open", "option", "order", "other", "our", "out", "outside", "over",
    "own", "page", "paper", "parent", "park", "part", "party", "password",
    "past", "pause", "pay", "people", "perfect", "person", "phone", "photo",
    "pick", "picture", "place", "plan", "play", "player", "please", "point",
    "police", "possible", "post", "power", "press", "pretty", "price",
    "print", "private", "probably", "problem", "process", "product",
    "profile", "program", "project", "public", "pull", "push", "put",
    "question", "quick", "quiet", "quite", "radio", "rain", "raise", "range",
    "rate", "read", "ready", "real", "really", "reason", "receive", "recent",
    "record", "red", "release", "remember", "remind", "remote", "remove",
    "reply", "report", "request", "reset", "rest", "restart", "restaurant",
    "result", "return", "review", "right", "ring", "road", "room", "run",
    "safe", "same", "save", "say", "school", "screen", "search", "second",
    "secret", "section", "see", "select", "sell", "send", "sense", "server",
    "service", "set", "setting", "several", "share", "she", "shop", "short",
    "should", "show", "shower", "sick", "side", "sign", "signal", "simple",
    "since", "single", "sister", "site", "size", "sleep", "slow", "small",
    "smart", "smile", "social", "software", "some", "someone", "something",
    "sometimes", "song", "soon", "sorry", "sound", "source", "space", "speak",
    "special", "speed", "spend", "sport", "stand", "start", "state", "station",
    "status", "stay", "step", "still", "stop", "store", "story", "street",
    "strong", "student", "study", "stuff", "style", "submit", "success",
    "such", "suggest", "summer", "sunday", "support", "sure", "switch",
    "system", "table", "take", "talk", "target", "task", "team", "tell",
    "test", "text", "than", "thank", "thanks", "that", "the", "their", "them",
    "then", "there", "these", "they", "thing", "think", "this", "those",
    "thought", "through", "time", "today", "together", "tomorrow", "tonight",
    "too", "tool", "top", "total", "touch", "traffic", "train", "transfer",
    "travel", "try", "turn", "type", "under", "understand", "until", "update",
    "upload", "use", "user", "usually", "value", "version", "very", "video",
    "view", "visit", "voice", "wait", "wake", "walk", "want", "warm", "watch",
    "water", "way", "weather", "week", "weekend", "welcome", "well", "were",
    "what", "when", "where", "which", "while", "white", "who", "whole", "why",
    "wifi", "will", "window", "windows", "winter", "wish", "with", "without",
    "woman", "wonderful", "word", "work", "world", "worry", "would", "write",
    "wrong", "yeah", "year", "yes", "yesterday", "yet", "you", "your",
};

const int g_en_words_count = (int)(sizeof(g_en_words) / sizeof(g_en_words[0]));
