from building import *
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add LittlevGL common include
src = src + Glob('*.c')

LOCAL_CCFLAGS = ''

group = DefineGroup('App_tv_remote', src, depend = [''], CPPPATH = inc, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
