from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

group = DefineGroup('lvgl_v8_multroller_src', src,
                    depend=['PKG_USING_LITTLEVGL2RTT'],
                    CPPPATH=[cwd])
Return('group')
