# for module compiling
import os
from building import *

cwd = GetCurrentDir()
objs = []
list = ['macif']

if GetDepend(['AIC_CFG_RDATA_MODE_EN']):
    list += ['rdata']
if GetDepend(['AIC_CFG_VNET_MODE_EN']):
    list += ['vnet']

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
