import os
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

# Add source code
src = Glob('main.c')
src += Glob('bap_broadcast_src_api.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
