from building import *
Import('rtconfig')

src   = []
CPPPATH = []
cwd   = GetCurrentDir()

if GetDepend('USING_ACPU_CTRL_FWK'):
    src += ['acpu_ctrl.c']

CPPPATH += [cwd+'/../include']    

# add src and include to group.
group = DefineGroup('middleware', src, depend = [],CPPPATH = CPPPATH)
    
Return('group')
