CONFIG_LXT_DISABLE=y
CONFIG_BSP_USING_ADC=y
CONFIG_BSP_USING_EPIC=y
CONFIG_BSP_USING_GPIO=y
CONFIG_BSP_USING_I2C1=y
CONFIG_BSP_USING_I2C2=y
CONFIG_BSP_USING_LCPU_PATCH=y
CONFIG_BSP_USING_PINMUX=y
CONFIG_BSP_USING_PWM=y
CONFIG_BSP_USING_PWM1=y
CONFIG_BSP_USING_PWMA1=y
CONFIG_BSP_USING_ONCHIP_RTC=y
CONFIG_BSP_USING_SPI=y
CONFIG_BSP_USING_TIM=y
CONFIG_BSP_USING_BTIM1=y
CONFIG_BSP_USING_LPTIM1=y
CONFIG_BSP_USING_UART=y
CONFIG_BSP_USING_UART1=y
CONFIG_BSP_UART1_RX_USING_DMA=y
CONFIG_BSP_USING_KEY1=y
CONFIG_BSP_KEY1_PIN=34
CONFIG_BSP_KEY1_ACTIVE_HIGH=y
