/*
 * SPDX-FileCopyrightText: 2019-2025 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef LV_CONF_KCONFIG_REMAP_V9_H
#define LV_CONF_KCONFIG_REMAP_V9_H

#ifndef DISABLE_LVGL_V9

#ifdef __cplusplus
extern "C" {
#endif

/*******************
 * STDLIB MALLOC
 *******************/

#ifdef LV_USE_BUILTIN_MALLOC
#define CONFIG_LV_USE_BUILTIN_MALLOC LV_USE_BUILTIN_MALLOC
#endif

#ifdef LV_USE_CLIB_MALLOC
#define CONFIG_LV_USE_CLIB_MALLOC LV_USE_CLIB_MALLOC
#endif

#ifdef LV_USE_MICROPYTHON_MALLOC
#define CONFIG_LV_USE_MICROPYTHON_MALLOC LV_USE_MICROPYTHON_MALLOC
#endif

#ifdef LV_USE_RTTHREAD_MALLOC
#define CONFIG_LV_USE_RTTHREAD_MALLOC LV_USE_RTTHREAD_MALLOC
#endif

#ifdef LV_USE_CUSTOM_MALLOC
#define CONFIG_LV_USE_CUSTOM_MALLOC LV_USE_CUSTOM_MALLOC
#endif

/*******************
 * STDLIB STRING
 *******************/

#ifdef LV_USE_BUILTIN_STRING
#define CONFIG_LV_USE_BUILTIN_STRING LV_USE_BUILTIN_STRING
#endif

#ifdef LV_USE_CLIB_STRING
#define CONFIG_LV_USE_CLIB_STRING LV_USE_CLIB_STRING
#endif

#ifdef LV_USE_MICROPYTHON_STRING
#define CONFIG_LV_USE_MICROPYTHON_STRING LV_USE_MICROPYTHON_STRING
#endif

#ifdef LV_USE_RTTHREAD_STRING
#define CONFIG_LV_USE_RTTHREAD_STRING LV_USE_RTTHREAD_STRING
#endif

#ifdef LV_USE_CUSTOM_STRING
#define CONFIG_LV_USE_CUSTOM_STRING LV_USE_CUSTOM_STRING
#endif

/*******************
 * STDLIB SPRINTF
 *******************/

#ifdef LV_USE_BUILTIN_SPRINTF
#define CONFIG_LV_USE_BUILTIN_SPRINTF LV_USE_BUILTIN_SPRINTF
#endif

#ifdef LV_USE_CLIB_SPRINTF
#define CONFIG_LV_USE_CLIB_SPRINTF LV_USE_CLIB_SPRINTF
#endif

#ifdef LV_USE_MICROPYTHON_SPRINTF
#define CONFIG_LV_USE_MICROPYTHON_SPRINTF LV_USE_MICROPYTHON_SPRINTF
#endif

#ifdef LV_USE_RTTHREAD_SPRINTF
#define CONFIG_LV_USE_RTTHREAD_SPRINTF LV_USE_RTTHREAD_SPRINTF
#endif

#ifdef LV_USE_CUSTOM_SPRINTF
#define CONFIG_LV_USE_CUSTOM_SPRINTF LV_USE_CUSTOM_SPRINTF
#endif

/*******************
 * MEMORY SIZE
 *******************/

#ifdef LV_MEM_SIZE_KILOBYTES
#define CONFIG_LV_MEM_SIZE_KILOBYTES LV_MEM_SIZE_KILOBYTES
#endif

#ifdef LV_MEM_POOL_EXPAND_SIZE_KILOBYTES
#define CONFIG_LV_MEM_POOL_EXPAND_SIZE_KILOBYTES LV_MEM_POOL_EXPAND_SIZE_KILOBYTES
#endif

/*******************
 * PERF MONITOR ALIGNMENT
 *******************/

#ifdef LV_PERF_MONITOR_ALIGN_TOP_LEFT
#define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_LEFT LV_PERF_MONITOR_ALIGN_TOP_LEFT
#endif

#ifdef LV_USE_PERF_MONITOR_ALIGN_TOP_MID
#define CONFIG_LV_USE_PERF_MONITOR_ALIGN_TOP_MID LV_USE_PERF_MONITOR_ALIGN_TOP_MID
#endif

#ifdef LV_PERF_MONITOR_ALIGN_TOP_RIGHT
#define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_RIGHT LV_PERF_MONITOR_ALIGN_TOP_RIGHT
#endif

#ifdef LV_PERF_MONITOR_ALIGN_BOTTOM_LEFT
#define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_LEFT LV_PERF_MONITOR_ALIGN_BOTTOM_LEFT
#endif

#ifdef LV_PERF_MONITOR_ALIGN_BOTTOM_MID
#define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_MID LV_PERF_MONITOR_ALIGN_BOTTOM_MID
#endif

#ifdef LV_PERF_MONITOR_ALIGN_BOTTOM_RIGHT
#define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_RIGHT LV_PERF_MONITOR_ALIGN_BOTTOM_RIGHT
#endif

#ifdef LV_PERF_MONITOR_ALIGN_LEFT_MID
#define CONFIG_LV_PERF_MONITOR_ALIGN_LEFT_MID LV_PERF_MONITOR_ALIGN_LEFT_MID
#endif

#ifdef LV_PERF_MONITOR_ALIGN_RIGHT_MID
#define CONFIG_LV_PERF_MONITOR_ALIGN_RIGHT_MID LV_PERF_MONITOR_ALIGN_RIGHT_MID
#endif

#ifdef LV_PERF_MONITOR_ALIGN_CENTER
#define CONFIG_LV_PERF_MONITOR_ALIGN_CENTER LV_PERF_MONITOR_ALIGN_CENTER
#endif

/*******************
 * MEM MONITOR ALIGNMENT
 *******************/

#ifdef LV_MEM_MONITOR_ALIGN_TOP_LEFT
#define CONFIG_LV_MEM_MONITOR_ALIGN_TOP_LEFT LV_MEM_MONITOR_ALIGN_TOP_LEFT
#endif

#ifdef LV_USE_MEM_MONITOR_ALIGN_TOP_MID
#define CONFIG_LV_USE_MEM_MONITOR_ALIGN_TOP_MID LV_USE_MEM_MONITOR_ALIGN_TOP_MID
#endif

#ifdef LV_MEM_MONITOR_ALIGN_TOP_RIGHT
#define CONFIG_LV_MEM_MONITOR_ALIGN_TOP_RIGHT LV_MEM_MONITOR_ALIGN_TOP_RIGHT
#endif

#ifdef LV_MEM_MONITOR_ALIGN_BOTTOM_LEFT
#define CONFIG_LV_MEM_MONITOR_ALIGN_BOTTOM_LEFT LV_MEM_MONITOR_ALIGN_BOTTOM_LEFT
#endif

#ifdef LV_MEM_MONITOR_ALIGN_BOTTOM_MID
#define CONFIG_LV_MEM_MONITOR_ALIGN_BOTTOM_MID LV_MEM_MONITOR_ALIGN_BOTTOM_MID
#endif

#ifdef LV_MEM_MONITOR_ALIGN_BOTTOM_RIGHT
#define CONFIG_LV_MEM_MONITOR_ALIGN_BOTTOM_RIGHT LV_MEM_MONITOR_ALIGN_BOTTOM_RIGHT
#endif

#ifdef LV_MEM_MONITOR_ALIGN_LEFT_MID
#define CONFIG_LV_MEM_MONITOR_ALIGN_LEFT_MID LV_MEM_MONITOR_ALIGN_LEFT_MID
#endif

#ifdef LV_MEM_MONITOR_ALIGN_RIGHT_MID
#define CONFIG_LV_MEM_MONITOR_ALIGN_RIGHT_MID LV_MEM_MONITOR_ALIGN_RIGHT_MID
#endif

#ifdef LV_MEM_MONITOR_ALIGN_CENTER
#define CONFIG_LV_MEM_MONITOR_ALIGN_CENTER LV_MEM_MONITOR_ALIGN_CENTER
#endif

/*******************
 * FONT DEFAULT
 *******************/

#ifdef LV_FONT_DEFAULT_MONTSERRAT_8
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_8 LV_FONT_DEFAULT_MONTSERRAT_8
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_10
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_10 LV_FONT_DEFAULT_MONTSERRAT_10
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_12
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_12 LV_FONT_DEFAULT_MONTSERRAT_12
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_14
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_14 LV_FONT_DEFAULT_MONTSERRAT_14
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_16
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16 LV_FONT_DEFAULT_MONTSERRAT_16
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_18
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_18 LV_FONT_DEFAULT_MONTSERRAT_18
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_20
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20 LV_FONT_DEFAULT_MONTSERRAT_20
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_22
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_22 LV_FONT_DEFAULT_MONTSERRAT_22
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_24
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_24 LV_FONT_DEFAULT_MONTSERRAT_24
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_26
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26 LV_FONT_DEFAULT_MONTSERRAT_26
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_28
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28 LV_FONT_DEFAULT_MONTSERRAT_28
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_30
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_30 LV_FONT_DEFAULT_MONTSERRAT_30
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_32
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_32 LV_FONT_DEFAULT_MONTSERRAT_32
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_34
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_34 LV_FONT_DEFAULT_MONTSERRAT_34
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_36
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_36 LV_FONT_DEFAULT_MONTSERRAT_36
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_38
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_38 LV_FONT_DEFAULT_MONTSERRAT_38
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_40
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_40 LV_FONT_DEFAULT_MONTSERRAT_40
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_42
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_42 LV_FONT_DEFAULT_MONTSERRAT_42
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_44
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_44 LV_FONT_DEFAULT_MONTSERRAT_44
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_46
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_46 LV_FONT_DEFAULT_MONTSERRAT_46
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_48
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_48 LV_FONT_DEFAULT_MONTSERRAT_48
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_12_SUBPX
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_12_SUBPX LV_FONT_DEFAULT_MONTSERRAT_12_SUBPX
#endif

#ifdef LV_FONT_DEFAULT_MONTSERRAT_28_COMPRESSED
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28_COMPRESSED LV_FONT_DEFAULT_MONTSERRAT_28_COMPRESSED
#endif

#ifdef LV_FONT_DEFAULT_DEJAVU_16_PERSIAN_HEBREW
#define CONFIG_LV_FONT_DEFAULT_DEJAVU_16_PERSIAN_HEBREW LV_FONT_DEFAULT_DEJAVU_16_PERSIAN_HEBREW
#endif

#ifdef LV_FONT_DEFAULT_SIMSUN_14_CJK
#define CONFIG_LV_FONT_DEFAULT_SIMSUN_14_CJK LV_FONT_DEFAULT_SIMSUN_14_CJK
#endif

#ifdef LV_FONT_DEFAULT_SIMSUN_16_CJK
#define CONFIG_LV_FONT_DEFAULT_SIMSUN_16_CJK LV_FONT_DEFAULT_SIMSUN_16_CJK
#endif

#ifdef LV_FONT_DEFAULT_UNSCII_8
#define CONFIG_LV_FONT_DEFAULT_UNSCII_8 LV_FONT_DEFAULT_UNSCII_8
#endif

#ifdef LV_FONT_DEFAULT_UNSCII_16
#define CONFIG_LV_FONT_DEFAULT_UNSCII_16 LV_FONT_DEFAULT_UNSCII_16
#endif

#ifdef LV_FONT_DEFAULT_SIMYOU_30_CH
#define CONFIG_LV_FONT_DEFAULT_SIMYOU_30_CH LV_FONT_DEFAULT_SIMYOU_30_CH
#endif

#ifdef LV_FONT_DEFAULT_UBUNTU_12
#define CONFIG_LV_FONT_DEFAULT_UBUNTU_12 LV_FONT_DEFAULT_UBUNTU_12
#endif

#ifdef LV_FONT_DEFAULT_UBUNTU_14
#define CONFIG_LV_FONT_DEFAULT_UBUNTU_14 LV_FONT_DEFAULT_UBUNTU_14
#endif

#ifdef LV_FONT_DEFAULT_UBUNTU_16
#define CONFIG_LV_FONT_DEFAULT_UBUNTU_16 LV_FONT_DEFAULT_UBUNTU_16
#endif

#ifdef LV_FONT_DEFAULT_UBUNTU_18
#define CONFIG_LV_FONT_DEFAULT_UBUNTU_18 LV_FONT_DEFAULT_UBUNTU_18
#endif

#ifdef LV_FONT_DEFAULT_UBUNTU_20
#define CONFIG_LV_FONT_DEFAULT_UBUNTU_20 LV_FONT_DEFAULT_UBUNTU_20
#endif

#ifdef LV_FONT_DEFAULT_UBUNTU_24
#define CONFIG_LV_FONT_DEFAULT_UBUNTU_24 LV_FONT_DEFAULT_UBUNTU_24
#endif

/*******************
 * TEXT ENCODING
 *******************/

#ifdef LV_TXT_ENC_UTF8
#define CONFIG_LV_TXT_ENC_UTF8 LV_TXT_ENC_UTF8
#endif

#ifdef LV_TXT_ENC_ASCII
#define CONFIG_LV_TXT_ENC_ASCII LV_TXT_ENC_ASCII
#endif

/*******************
 * BIDI DIRECTION
 *******************/

#ifdef LV_BASE_DIR_LTR
#define CONFIG_LV_BASE_DIR_LTR LV_BASE_DIR_LTR
#endif

#ifdef LV_BASE_DIR_RTL
#define CONFIG_LV_BASE_DIR_RTL LV_BASE_DIR_RTL
#endif

#ifdef LV_BASE_DIR_AUTO
#define CONFIG_LV_BASE_DIR_AUTO LV_BASE_DIR_AUTO
#endif

/*******************
 * SDL RENDER MODE
 *******************/

#ifdef LV_SDL_RENDER_MODE_PARTIAL
#define CONFIG_LV_SDL_RENDER_MODE_PARTIAL LV_SDL_RENDER_MODE_PARTIAL
#endif

#ifdef LV_SDL_RENDER_MODE_DIRECT
#define CONFIG_LV_SDL_RENDER_MODE_DIRECT LV_SDL_RENDER_MODE_DIRECT
#endif

#ifdef LV_SDL_RENDER_MODE_FULL
#define CONFIG_LV_SDL_RENDER_MODE_FULL LV_SDL_RENDER_MODE_FULL
#endif

/*******************
 * LINUX FBDEV RENDER MODE
 *******************/

#ifdef LV_LINUX_FBDEV_RENDER_MODE_PARTIAL
#define CONFIG_LV_LINUX_FBDEV_RENDER_MODE_PARTIAL LV_LINUX_FBDEV_RENDER_MODE_PARTIAL
#endif

#ifdef LV_LINUX_FBDEV_RENDER_MODE_DIRECT
#define CONFIG_LV_LINUX_FBDEV_RENDER_MODE_DIRECT LV_LINUX_FBDEV_RENDER_MODE_DIRECT
#endif

#ifdef LV_LINUX_FBDEV_RENDER_MODE_FULL
#define CONFIG_LV_LINUX_FBDEV_RENDER_MODE_FULL LV_LINUX_FBDEV_RENDER_MODE_FULL
#endif

/*******************
 * OTHER MACROS
 *******************/

#ifdef LV_CONF_KCONFIG_EXTERNAL_INCLUDE
#define CONFIG_LV_CONF_KCONFIG_EXTERNAL_INCLUDE LV_CONF_KCONFIG_EXTERNAL_INCLUDE
#endif

#ifdef ESP_PLATFORM
#define CONFIG_ESP_PLATFORM ESP_PLATFORM
#endif

#ifdef LV_CONF_INCLUDE_SIMPLE
#define CONFIG_LV_CONF_INCLUDE_SIMPLE LV_CONF_INCLUDE_SIMPLE
#endif

#ifdef LV_USE_STDLIB_MALLOC
#define CONFIG_LV_USE_STDLIB_MALLOC LV_USE_STDLIB_MALLOC
#endif

#ifdef LV_USE_STDLIB_STRING
#define CONFIG_LV_USE_STDLIB_STRING LV_USE_STDLIB_STRING
#endif

#ifdef LV_USE_STDLIB_SPRINTF
#define CONFIG_LV_USE_STDLIB_SPRINTF LV_USE_STDLIB_SPRINTF
#endif

#ifdef LV_MEM_SIZE
#define CONFIG_LV_MEM_SIZE LV_MEM_SIZE
#endif

#ifdef LV_MEM_POOL_EXPAND_SIZE
#define CONFIG_LV_MEM_POOL_EXPAND_SIZE LV_MEM_POOL_EXPAND_SIZE
#endif

#ifdef LV_USE_PERF_MONITOR_POS
#define CONFIG_LV_USE_PERF_MONITOR_POS LV_USE_PERF_MONITOR_POS
#endif

#ifdef LV_USE_MEM_MONITOR_POS
#define CONFIG_LV_USE_MEM_MONITOR_POS LV_USE_MEM_MONITOR_POS
#endif

#ifdef LV_FONT_DEFAULT
#define CONFIG_LV_FONT_DEFAULT LV_FONT_DEFAULT
#endif

#ifdef LV_TXT_ENC
#define CONFIG_LV_TXT_ENC LV_TXT_ENC
#endif

#ifdef LV_BIDI_BASE_DIR_DEF
#define CONFIG_LV_BIDI_BASE_DIR_DEF LV_BIDI_BASE_DIR_DEF
#endif

#ifdef LV_SDL_RENDER_MODE
#define CONFIG_LV_SDL_RENDER_MODE LV_SDL_RENDER_MODE
#endif

#ifdef LV_LINUX_FBDEV_RENDER_MODE
#define CONFIG_LV_LINUX_FBDEV_RENDER_MODE LV_LINUX_FBDEV_RENDER_MODE
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

#endif /*LV_CONF_KCONFIG_REMAP_V9_H*/