CONFIG_BT_TX_POWER_VAL=y
CONFIG_BSP_USING_SPI=y
CONFIG_BSP_USING_SPI_DMA_CIRCULAR=y
CONFIG_BSP_USING_SPI1=y
CONFIG_BSP_SPI1_TX_USING_DMA=y
CONFIG_BSP_SPI1_RX_USING_DMA=y
CONFIG_BSP_USING_SPI2=y
CONFIG_BSP_SPI2_TX_USING_DMA=y
CONFIG_BSP_SPI2_RX_USING_DMA=y
CONFIG_RT_MAIN_THREAD_STACK_SIZE=4096
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_USING_ISR_LOG=y
