import os
from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = ['core_dump.c']
inc = [cwd]

# add group to IDE project
objs = DefineGroup('middleware', src, depend = ['USING_CORE_DUMP'], CPPPATH = inc)
Return('objs')
