from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]
group = DefineGroup('Drivers', src, depend = ['SENSOR_USING_HUMITURE', 'HUMITURE_USING_SHT30'], CPPPATH = path, LIBPATH = path)

Return('group')
