Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

CPPPATH = [cwd]

src = Glob('*.c')

group = DefineGroup('audio', src,depend = ['PKG_USING_I2S_MODEM'],CPPPATH = CPPPATH)

Return('group')
