/*
 * SPDX-FileCopyrightText: 2026 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __SECU1_H
#define __SECU1_H

#define SECU_VERSION    (2)

typedef struct
{
    __IO uint32_t SECU_CTRL;
    __IO uint32_t IRQ_STAT0;
    __IO uint32_t IRQ_STAT1;
    __IO uint32_t IRQ_CFG0;
    __IO uint32_t IRQ_CFG1;
    __IO uint32_t HPMST_ATTR_CFG;
    __IO uint32_t HPSLV_ATTR_CFG;
    __IO uint32_t MPI1_R0_CFG0;
    __IO uint32_t MPI1_R0_CFG1;
    __IO uint32_t MPI1_R1_CFG0;
    __IO uint32_t MPI1_R1_CFG1;
    __IO uint32_t MPI1_R2_CFG0;
    __IO uint32_t MPI1_R2_CFG1;
    __IO uint32_t MPI1_RW_CFG;
    __IO uint32_t MPI2_R0_CFG0;
    __IO uint32_t MPI2_R0_CFG1;
    __IO uint32_t MPI2_R1_CFG0;
    __IO uint32_t MPI2_R1_CFG1;
    __IO uint32_t MPI2_R2_CFG0;
    __IO uint32_t MPI2_R2_CFG1;
    __IO uint32_t MPI2_RW_CFG;
    __IO uint32_t MPI3_R0_CFG0;
    __IO uint32_t MPI3_R0_CFG1;
    __IO uint32_t MPI3_R1_CFG0;
    __IO uint32_t MPI3_R1_CFG1;
    __IO uint32_t MPI3_R2_CFG0;
    __IO uint32_t MPI3_R2_CFG1;
    __IO uint32_t MPI3_RW_CFG;
    __IO uint32_t RAM0_R0_CFG0;
    __IO uint32_t RAM0_R0_CFG1;
    __IO uint32_t RAM0_R1_CFG0;
    __IO uint32_t RAM0_R1_CFG1;
    __IO uint32_t RAM0_RW_ATTR;
    __IO uint32_t RAM1_R0_CFG0;
    __IO uint32_t RAM1_R0_CFG1;
    __IO uint32_t RAM1_R1_CFG0;
    __IO uint32_t RAM1_R1_CFG1;
    __IO uint32_t RAM1_RW_ATTR;
    __IO uint32_t RAM2_R0_CFG0;
    __IO uint32_t RAM2_R0_CFG1;
    __IO uint32_t RAM2_R1_CFG0;
    __IO uint32_t RAM2_R1_CFG1;
    __IO uint32_t RAM2_RW_ATTR;
    __IO uint32_t ACPU;
    __IO uint32_t MISC;
    __IO uint32_t DBG_CODE0;
    __IO uint32_t DBG_CODE1;
    __IO uint32_t DBG_CODE2;
    __IO uint32_t DBG_CODE3;
    __IO uint32_t AHB_ACC_CFG;
    __IO uint32_t APB1_ACC_CFG;
    __IO uint32_t APB2_ACC_CFG;
    __IO uint32_t APB3_ACC_CFG;
    __IO uint32_t APB4_ACC_CFG;
} SECU1_TypeDef;


/**************** Bit definition for SECU1_SECU_CTRL register *****************/
#define SECU1_SECU_CTRL_HPMST_LOCK_Pos  (0U)
#define SECU1_SECU_CTRL_HPMST_LOCK_Msk  (0x1UL << SECU1_SECU_CTRL_HPMST_LOCK_Pos)
#define SECU1_SECU_CTRL_HPMST_LOCK      SECU1_SECU_CTRL_HPMST_LOCK_Msk
#define SECU1_SECU_CTRL_HPSLV_LOCK_Pos  (1U)
#define SECU1_SECU_CTRL_HPSLV_LOCK_Msk  (0x1UL << SECU1_SECU_CTRL_HPSLV_LOCK_Pos)
#define SECU1_SECU_CTRL_HPSLV_LOCK      SECU1_SECU_CTRL_HPSLV_LOCK_Msk
#define SECU1_SECU_CTRL_MPI1_LOCK_Pos   (2U)
#define SECU1_SECU_CTRL_MPI1_LOCK_Msk   (0x1UL << SECU1_SECU_CTRL_MPI1_LOCK_Pos)
#define SECU1_SECU_CTRL_MPI1_LOCK       SECU1_SECU_CTRL_MPI1_LOCK_Msk
#define SECU1_SECU_CTRL_MPI2_LOCK_Pos   (3U)
#define SECU1_SECU_CTRL_MPI2_LOCK_Msk   (0x1UL << SECU1_SECU_CTRL_MPI2_LOCK_Pos)
#define SECU1_SECU_CTRL_MPI2_LOCK       SECU1_SECU_CTRL_MPI2_LOCK_Msk
#define SECU1_SECU_CTRL_MPI3_LOCK_Pos   (4U)
#define SECU1_SECU_CTRL_MPI3_LOCK_Msk   (0x1UL << SECU1_SECU_CTRL_MPI3_LOCK_Pos)
#define SECU1_SECU_CTRL_MPI3_LOCK       SECU1_SECU_CTRL_MPI3_LOCK_Msk
#define SECU1_SECU_CTRL_RAM_LOCK_Pos    (5U)
#define SECU1_SECU_CTRL_RAM_LOCK_Msk    (0x1UL << SECU1_SECU_CTRL_RAM_LOCK_Pos)
#define SECU1_SECU_CTRL_RAM_LOCK        SECU1_SECU_CTRL_RAM_LOCK_Msk
#define SECU1_SECU_CTRL_DBG_CODE_LOCK_Pos  (6U)
#define SECU1_SECU_CTRL_DBG_CODE_LOCK_Msk  (0x1UL << SECU1_SECU_CTRL_DBG_CODE_LOCK_Pos)
#define SECU1_SECU_CTRL_DBG_CODE_LOCK   SECU1_SECU_CTRL_DBG_CODE_LOCK_Msk
#define SECU1_SECU_CTRL_HPMST_ATTR_UPDATE_Pos  (8U)
#define SECU1_SECU_CTRL_HPMST_ATTR_UPDATE_Msk  (0x1UL << SECU1_SECU_CTRL_HPMST_ATTR_UPDATE_Pos)
#define SECU1_SECU_CTRL_HPMST_ATTR_UPDATE  SECU1_SECU_CTRL_HPMST_ATTR_UPDATE_Msk

/**************** Bit definition for SECU1_IRQ_STAT0 register *****************/
#define SECU1_IRQ_STAT0_ILL_PTC1_PRIV_W_Pos  (0U)
#define SECU1_IRQ_STAT0_ILL_PTC1_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_PTC1_PRIV_W_Pos)
#define SECU1_IRQ_STAT0_ILL_PTC1_PRIV_W  SECU1_IRQ_STAT0_ILL_PTC1_PRIV_W_Msk
#define SECU1_IRQ_STAT0_ILL_PTC1_PRIV_R_Pos  (1U)
#define SECU1_IRQ_STAT0_ILL_PTC1_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_PTC1_PRIV_R_Pos)
#define SECU1_IRQ_STAT0_ILL_PTC1_PRIV_R  SECU1_IRQ_STAT0_ILL_PTC1_PRIV_R_Msk
#define SECU1_IRQ_STAT0_ILL_PTC1_SEC_W_Pos  (2U)
#define SECU1_IRQ_STAT0_ILL_PTC1_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_PTC1_SEC_W_Pos)
#define SECU1_IRQ_STAT0_ILL_PTC1_SEC_W  SECU1_IRQ_STAT0_ILL_PTC1_SEC_W_Msk
#define SECU1_IRQ_STAT0_ILL_PTC1_SEC_R_Pos  (3U)
#define SECU1_IRQ_STAT0_ILL_PTC1_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_PTC1_SEC_R_Pos)
#define SECU1_IRQ_STAT0_ILL_PTC1_SEC_R  SECU1_IRQ_STAT0_ILL_PTC1_SEC_R_Msk
#define SECU1_IRQ_STAT0_ILL_TRNG_PRIV_W_Pos  (4U)
#define SECU1_IRQ_STAT0_ILL_TRNG_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_TRNG_PRIV_W_Pos)
#define SECU1_IRQ_STAT0_ILL_TRNG_PRIV_W  SECU1_IRQ_STAT0_ILL_TRNG_PRIV_W_Msk
#define SECU1_IRQ_STAT0_ILL_TRNG_PRIV_R_Pos  (5U)
#define SECU1_IRQ_STAT0_ILL_TRNG_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_TRNG_PRIV_R_Pos)
#define SECU1_IRQ_STAT0_ILL_TRNG_PRIV_R  SECU1_IRQ_STAT0_ILL_TRNG_PRIV_R_Msk
#define SECU1_IRQ_STAT0_ILL_TRNG_SEC_W_Pos  (6U)
#define SECU1_IRQ_STAT0_ILL_TRNG_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_TRNG_SEC_W_Pos)
#define SECU1_IRQ_STAT0_ILL_TRNG_SEC_W  SECU1_IRQ_STAT0_ILL_TRNG_SEC_W_Msk
#define SECU1_IRQ_STAT0_ILL_TRNG_SEC_R_Pos  (7U)
#define SECU1_IRQ_STAT0_ILL_TRNG_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_TRNG_SEC_R_Pos)
#define SECU1_IRQ_STAT0_ILL_TRNG_SEC_R  SECU1_IRQ_STAT0_ILL_TRNG_SEC_R_Msk
#define SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_W_Pos  (8U)
#define SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_W_Pos)
#define SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_W  SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_W_Msk
#define SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_R_Pos  (9U)
#define SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_R_Pos)
#define SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_R  SECU1_IRQ_STAT0_ILL_EFUSE_PRIV_R_Msk
#define SECU1_IRQ_STAT0_ILL_EFUSE_SEC_W_Pos  (10U)
#define SECU1_IRQ_STAT0_ILL_EFUSE_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_EFUSE_SEC_W_Pos)
#define SECU1_IRQ_STAT0_ILL_EFUSE_SEC_W  SECU1_IRQ_STAT0_ILL_EFUSE_SEC_W_Msk
#define SECU1_IRQ_STAT0_ILL_EFUSE_SEC_R_Pos  (11U)
#define SECU1_IRQ_STAT0_ILL_EFUSE_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_EFUSE_SEC_R_Pos)
#define SECU1_IRQ_STAT0_ILL_EFUSE_SEC_R  SECU1_IRQ_STAT0_ILL_EFUSE_SEC_R_Msk
#define SECU1_IRQ_STAT0_ILL_AES_PRIV_W_Pos  (12U)
#define SECU1_IRQ_STAT0_ILL_AES_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_AES_PRIV_W_Pos)
#define SECU1_IRQ_STAT0_ILL_AES_PRIV_W  SECU1_IRQ_STAT0_ILL_AES_PRIV_W_Msk
#define SECU1_IRQ_STAT0_ILL_AES_PRIV_R_Pos  (13U)
#define SECU1_IRQ_STAT0_ILL_AES_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_AES_PRIV_R_Pos)
#define SECU1_IRQ_STAT0_ILL_AES_PRIV_R  SECU1_IRQ_STAT0_ILL_AES_PRIV_R_Msk
#define SECU1_IRQ_STAT0_ILL_AES_SEC_W_Pos  (14U)
#define SECU1_IRQ_STAT0_ILL_AES_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_AES_SEC_W_Pos)
#define SECU1_IRQ_STAT0_ILL_AES_SEC_W   SECU1_IRQ_STAT0_ILL_AES_SEC_W_Msk
#define SECU1_IRQ_STAT0_ILL_AES_SEC_R_Pos  (15U)
#define SECU1_IRQ_STAT0_ILL_AES_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_AES_SEC_R_Pos)
#define SECU1_IRQ_STAT0_ILL_AES_SEC_R   SECU1_IRQ_STAT0_ILL_AES_SEC_R_Msk
#define SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_W_Pos  (16U)
#define SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_W_Pos)
#define SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_W  SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_W_Msk
#define SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_R_Pos  (17U)
#define SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_R_Pos)
#define SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_R  SECU1_IRQ_STAT0_ILL_DMAC1_PRIV_R_Msk
#define SECU1_IRQ_STAT0_ILL_DMAC1_SEC_W_Pos  (18U)
#define SECU1_IRQ_STAT0_ILL_DMAC1_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_DMAC1_SEC_W_Pos)
#define SECU1_IRQ_STAT0_ILL_DMAC1_SEC_W  SECU1_IRQ_STAT0_ILL_DMAC1_SEC_W_Msk
#define SECU1_IRQ_STAT0_ILL_DMAC1_SEC_R_Pos  (19U)
#define SECU1_IRQ_STAT0_ILL_DMAC1_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_DMAC1_SEC_R_Pos)
#define SECU1_IRQ_STAT0_ILL_DMAC1_SEC_R  SECU1_IRQ_STAT0_ILL_DMAC1_SEC_R_Msk
#define SECU1_IRQ_STAT0_ILL_SECU1_PRIV_W_Pos  (20U)
#define SECU1_IRQ_STAT0_ILL_SECU1_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_SECU1_PRIV_W_Pos)
#define SECU1_IRQ_STAT0_ILL_SECU1_PRIV_W  SECU1_IRQ_STAT0_ILL_SECU1_PRIV_W_Msk
#define SECU1_IRQ_STAT0_ILL_SECU1_PRIV_R_Pos  (21U)
#define SECU1_IRQ_STAT0_ILL_SECU1_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_SECU1_PRIV_R_Pos)
#define SECU1_IRQ_STAT0_ILL_SECU1_PRIV_R  SECU1_IRQ_STAT0_ILL_SECU1_PRIV_R_Msk
#define SECU1_IRQ_STAT0_ILL_SECU1_SEC_W_Pos  (22U)
#define SECU1_IRQ_STAT0_ILL_SECU1_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_SECU1_SEC_W_Pos)
#define SECU1_IRQ_STAT0_ILL_SECU1_SEC_W  SECU1_IRQ_STAT0_ILL_SECU1_SEC_W_Msk
#define SECU1_IRQ_STAT0_ILL_SECU1_SEC_R_Pos  (23U)
#define SECU1_IRQ_STAT0_ILL_SECU1_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT0_ILL_SECU1_SEC_R_Pos)
#define SECU1_IRQ_STAT0_ILL_SECU1_SEC_R  SECU1_IRQ_STAT0_ILL_SECU1_SEC_R_Msk

/**************** Bit definition for SECU1_IRQ_STAT1 register *****************/
#define SECU1_IRQ_STAT1_ILL_MPI1_PRIV_W_Pos  (0U)
#define SECU1_IRQ_STAT1_ILL_MPI1_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI1_PRIV_W_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI1_PRIV_W  SECU1_IRQ_STAT1_ILL_MPI1_PRIV_W_Msk
#define SECU1_IRQ_STAT1_ILL_MPI1_PRIV_R_Pos  (1U)
#define SECU1_IRQ_STAT1_ILL_MPI1_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI1_PRIV_R_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI1_PRIV_R  SECU1_IRQ_STAT1_ILL_MPI1_PRIV_R_Msk
#define SECU1_IRQ_STAT1_ILL_MPI1_SEC_W_Pos  (2U)
#define SECU1_IRQ_STAT1_ILL_MPI1_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI1_SEC_W_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI1_SEC_W  SECU1_IRQ_STAT1_ILL_MPI1_SEC_W_Msk
#define SECU1_IRQ_STAT1_ILL_MPI1_SEC_R_Pos  (3U)
#define SECU1_IRQ_STAT1_ILL_MPI1_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI1_SEC_R_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI1_SEC_R  SECU1_IRQ_STAT1_ILL_MPI1_SEC_R_Msk
#define SECU1_IRQ_STAT1_ILL_MPI2_PRIV_W_Pos  (4U)
#define SECU1_IRQ_STAT1_ILL_MPI2_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI2_PRIV_W_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI2_PRIV_W  SECU1_IRQ_STAT1_ILL_MPI2_PRIV_W_Msk
#define SECU1_IRQ_STAT1_ILL_MPI2_PRIV_R_Pos  (5U)
#define SECU1_IRQ_STAT1_ILL_MPI2_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI2_PRIV_R_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI2_PRIV_R  SECU1_IRQ_STAT1_ILL_MPI2_PRIV_R_Msk
#define SECU1_IRQ_STAT1_ILL_MPI2_SEC_W_Pos  (6U)
#define SECU1_IRQ_STAT1_ILL_MPI2_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI2_SEC_W_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI2_SEC_W  SECU1_IRQ_STAT1_ILL_MPI2_SEC_W_Msk
#define SECU1_IRQ_STAT1_ILL_MPI2_SEC_R_Pos  (7U)
#define SECU1_IRQ_STAT1_ILL_MPI2_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI2_SEC_R_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI2_SEC_R  SECU1_IRQ_STAT1_ILL_MPI2_SEC_R_Msk
#define SECU1_IRQ_STAT1_ILL_MPI3_PRIV_W_Pos  (8U)
#define SECU1_IRQ_STAT1_ILL_MPI3_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI3_PRIV_W_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI3_PRIV_W  SECU1_IRQ_STAT1_ILL_MPI3_PRIV_W_Msk
#define SECU1_IRQ_STAT1_ILL_MPI3_PRIV_R_Pos  (9U)
#define SECU1_IRQ_STAT1_ILL_MPI3_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI3_PRIV_R_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI3_PRIV_R  SECU1_IRQ_STAT1_ILL_MPI3_PRIV_R_Msk
#define SECU1_IRQ_STAT1_ILL_MPI3_SEC_W_Pos  (10U)
#define SECU1_IRQ_STAT1_ILL_MPI3_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI3_SEC_W_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI3_SEC_W  SECU1_IRQ_STAT1_ILL_MPI3_SEC_W_Msk
#define SECU1_IRQ_STAT1_ILL_MPI3_SEC_R_Pos  (11U)
#define SECU1_IRQ_STAT1_ILL_MPI3_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_MPI3_SEC_R_Pos)
#define SECU1_IRQ_STAT1_ILL_MPI3_SEC_R  SECU1_IRQ_STAT1_ILL_MPI3_SEC_R_Msk
#define SECU1_IRQ_STAT1_ILL_RAM0_PRIV_W_Pos  (12U)
#define SECU1_IRQ_STAT1_ILL_RAM0_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM0_PRIV_W_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM0_PRIV_W  SECU1_IRQ_STAT1_ILL_RAM0_PRIV_W_Msk
#define SECU1_IRQ_STAT1_ILL_RAM0_PRIV_R_Pos  (13U)
#define SECU1_IRQ_STAT1_ILL_RAM0_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM0_PRIV_R_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM0_PRIV_R  SECU1_IRQ_STAT1_ILL_RAM0_PRIV_R_Msk
#define SECU1_IRQ_STAT1_ILL_RAM0_SEC_W_Pos  (14U)
#define SECU1_IRQ_STAT1_ILL_RAM0_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM0_SEC_W_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM0_SEC_W  SECU1_IRQ_STAT1_ILL_RAM0_SEC_W_Msk
#define SECU1_IRQ_STAT1_ILL_RAM0_SEC_R_Pos  (15U)
#define SECU1_IRQ_STAT1_ILL_RAM0_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM0_SEC_R_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM0_SEC_R  SECU1_IRQ_STAT1_ILL_RAM0_SEC_R_Msk
#define SECU1_IRQ_STAT1_ILL_RAM1_PRIV_W_Pos  (16U)
#define SECU1_IRQ_STAT1_ILL_RAM1_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM1_PRIV_W_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM1_PRIV_W  SECU1_IRQ_STAT1_ILL_RAM1_PRIV_W_Msk
#define SECU1_IRQ_STAT1_ILL_RAM1_PRIV_R_Pos  (17U)
#define SECU1_IRQ_STAT1_ILL_RAM1_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM1_PRIV_R_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM1_PRIV_R  SECU1_IRQ_STAT1_ILL_RAM1_PRIV_R_Msk
#define SECU1_IRQ_STAT1_ILL_RAM1_SEC_W_Pos  (18U)
#define SECU1_IRQ_STAT1_ILL_RAM1_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM1_SEC_W_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM1_SEC_W  SECU1_IRQ_STAT1_ILL_RAM1_SEC_W_Msk
#define SECU1_IRQ_STAT1_ILL_RAM1_SEC_R_Pos  (19U)
#define SECU1_IRQ_STAT1_ILL_RAM1_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM1_SEC_R_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM1_SEC_R  SECU1_IRQ_STAT1_ILL_RAM1_SEC_R_Msk
#define SECU1_IRQ_STAT1_ILL_RAM2_PRIV_W_Pos  (20U)
#define SECU1_IRQ_STAT1_ILL_RAM2_PRIV_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM2_PRIV_W_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM2_PRIV_W  SECU1_IRQ_STAT1_ILL_RAM2_PRIV_W_Msk
#define SECU1_IRQ_STAT1_ILL_RAM2_PRIV_R_Pos  (21U)
#define SECU1_IRQ_STAT1_ILL_RAM2_PRIV_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM2_PRIV_R_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM2_PRIV_R  SECU1_IRQ_STAT1_ILL_RAM2_PRIV_R_Msk
#define SECU1_IRQ_STAT1_ILL_RAM2_SEC_W_Pos  (22U)
#define SECU1_IRQ_STAT1_ILL_RAM2_SEC_W_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM2_SEC_W_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM2_SEC_W  SECU1_IRQ_STAT1_ILL_RAM2_SEC_W_Msk
#define SECU1_IRQ_STAT1_ILL_RAM2_SEC_R_Pos  (23U)
#define SECU1_IRQ_STAT1_ILL_RAM2_SEC_R_Msk  (0x1UL << SECU1_IRQ_STAT1_ILL_RAM2_SEC_R_Pos)
#define SECU1_IRQ_STAT1_ILL_RAM2_SEC_R  SECU1_IRQ_STAT1_ILL_RAM2_SEC_R_Msk

/***************** Bit definition for SECU1_IRQ_CFG0 register *****************/
#define SECU1_IRQ_CFG0_ILL_PTC1_PRIV_W_MASK_Pos  (0U)
#define SECU1_IRQ_CFG0_ILL_PTC1_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_PTC1_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_PTC1_PRIV_W_MASK  SECU1_IRQ_CFG0_ILL_PTC1_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_PTC1_PRIV_R_MASK_Pos  (1U)
#define SECU1_IRQ_CFG0_ILL_PTC1_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_PTC1_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_PTC1_PRIV_R_MASK  SECU1_IRQ_CFG0_ILL_PTC1_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_PTC1_SEC_W_MASK_Pos  (2U)
#define SECU1_IRQ_CFG0_ILL_PTC1_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_PTC1_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_PTC1_SEC_W_MASK  SECU1_IRQ_CFG0_ILL_PTC1_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_PTC1_SEC_R_MASK_Pos  (3U)
#define SECU1_IRQ_CFG0_ILL_PTC1_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_PTC1_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_PTC1_SEC_R_MASK  SECU1_IRQ_CFG0_ILL_PTC1_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_TRNG_PRIV_W_MASK_Pos  (4U)
#define SECU1_IRQ_CFG0_ILL_TRNG_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_TRNG_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_TRNG_PRIV_W_MASK  SECU1_IRQ_CFG0_ILL_TRNG_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_TRNG_PRIV_R_MASK_Pos  (5U)
#define SECU1_IRQ_CFG0_ILL_TRNG_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_TRNG_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_TRNG_PRIV_R_MASK  SECU1_IRQ_CFG0_ILL_TRNG_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_TRNG_SEC_W_MASK_Pos  (6U)
#define SECU1_IRQ_CFG0_ILL_TRNG_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_TRNG_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_TRNG_SEC_W_MASK  SECU1_IRQ_CFG0_ILL_TRNG_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_TRNG_SEC_R_MASK_Pos  (7U)
#define SECU1_IRQ_CFG0_ILL_TRNG_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_TRNG_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_TRNG_SEC_R_MASK  SECU1_IRQ_CFG0_ILL_TRNG_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_W_MASK_Pos  (8U)
#define SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_W_MASK  SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_R_MASK_Pos  (9U)
#define SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_R_MASK  SECU1_IRQ_CFG0_ILL_EFUSE_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_EFUSE_SEC_W_MASK_Pos  (10U)
#define SECU1_IRQ_CFG0_ILL_EFUSE_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_EFUSE_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_EFUSE_SEC_W_MASK  SECU1_IRQ_CFG0_ILL_EFUSE_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_EFUSE_SEC_R_MASK_Pos  (11U)
#define SECU1_IRQ_CFG0_ILL_EFUSE_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_EFUSE_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_EFUSE_SEC_R_MASK  SECU1_IRQ_CFG0_ILL_EFUSE_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_AES_PRIV_W_MASK_Pos  (12U)
#define SECU1_IRQ_CFG0_ILL_AES_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_AES_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_AES_PRIV_W_MASK  SECU1_IRQ_CFG0_ILL_AES_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_AES_PRIV_R_MASK_Pos  (13U)
#define SECU1_IRQ_CFG0_ILL_AES_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_AES_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_AES_PRIV_R_MASK  SECU1_IRQ_CFG0_ILL_AES_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_AES_SEC_W_MASK_Pos  (14U)
#define SECU1_IRQ_CFG0_ILL_AES_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_AES_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_AES_SEC_W_MASK  SECU1_IRQ_CFG0_ILL_AES_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_AES_SEC_R_MASK_Pos  (15U)
#define SECU1_IRQ_CFG0_ILL_AES_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_AES_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_AES_SEC_R_MASK  SECU1_IRQ_CFG0_ILL_AES_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_W_MASK_Pos  (16U)
#define SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_W_MASK  SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_R_MASK_Pos  (17U)
#define SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_R_MASK  SECU1_IRQ_CFG0_ILL_DMAC1_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_DMAC1_SEC_W_MASK_Pos  (18U)
#define SECU1_IRQ_CFG0_ILL_DMAC1_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_DMAC1_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_DMAC1_SEC_W_MASK  SECU1_IRQ_CFG0_ILL_DMAC1_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_DMAC1_SEC_R_MASK_Pos  (19U)
#define SECU1_IRQ_CFG0_ILL_DMAC1_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_DMAC1_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_DMAC1_SEC_R_MASK  SECU1_IRQ_CFG0_ILL_DMAC1_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_SECU1_PRIV_W_MASK_Pos  (20U)
#define SECU1_IRQ_CFG0_ILL_SECU1_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_SECU1_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_SECU1_PRIV_W_MASK  SECU1_IRQ_CFG0_ILL_SECU1_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_SECU1_PRIV_R_MASK_Pos  (21U)
#define SECU1_IRQ_CFG0_ILL_SECU1_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_SECU1_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_SECU1_PRIV_R_MASK  SECU1_IRQ_CFG0_ILL_SECU1_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_SECU1_SEC_W_MASK_Pos  (22U)
#define SECU1_IRQ_CFG0_ILL_SECU1_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_SECU1_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_SECU1_SEC_W_MASK  SECU1_IRQ_CFG0_ILL_SECU1_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG0_ILL_SECU1_SEC_R_MASK_Pos  (23U)
#define SECU1_IRQ_CFG0_ILL_SECU1_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG0_ILL_SECU1_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG0_ILL_SECU1_SEC_R_MASK  SECU1_IRQ_CFG0_ILL_SECU1_SEC_R_MASK_Msk

/***************** Bit definition for SECU1_IRQ_CFG1 register *****************/
#define SECU1_IRQ_CFG1_ILL_MPI1_PRIV_W_MASK_Pos  (0U)
#define SECU1_IRQ_CFG1_ILL_MPI1_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI1_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI1_PRIV_W_MASK  SECU1_IRQ_CFG1_ILL_MPI1_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI1_PRIV_R_MASK_Pos  (1U)
#define SECU1_IRQ_CFG1_ILL_MPI1_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI1_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI1_PRIV_R_MASK  SECU1_IRQ_CFG1_ILL_MPI1_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI1_SEC_W_MASK_Pos  (2U)
#define SECU1_IRQ_CFG1_ILL_MPI1_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI1_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI1_SEC_W_MASK  SECU1_IRQ_CFG1_ILL_MPI1_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI1_SEC_R_MASK_Pos  (3U)
#define SECU1_IRQ_CFG1_ILL_MPI1_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI1_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI1_SEC_R_MASK  SECU1_IRQ_CFG1_ILL_MPI1_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI2_PRIV_W_MASK_Pos  (4U)
#define SECU1_IRQ_CFG1_ILL_MPI2_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI2_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI2_PRIV_W_MASK  SECU1_IRQ_CFG1_ILL_MPI2_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI2_PRIV_R_MASK_Pos  (5U)
#define SECU1_IRQ_CFG1_ILL_MPI2_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI2_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI2_PRIV_R_MASK  SECU1_IRQ_CFG1_ILL_MPI2_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI2_SEC_W_MASK_Pos  (6U)
#define SECU1_IRQ_CFG1_ILL_MPI2_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI2_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI2_SEC_W_MASK  SECU1_IRQ_CFG1_ILL_MPI2_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI2_SEC_R_MASK_Pos  (7U)
#define SECU1_IRQ_CFG1_ILL_MPI2_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI2_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI2_SEC_R_MASK  SECU1_IRQ_CFG1_ILL_MPI2_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI3_PRIV_W_MASK_Pos  (8U)
#define SECU1_IRQ_CFG1_ILL_MPI3_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI3_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI3_PRIV_W_MASK  SECU1_IRQ_CFG1_ILL_MPI3_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI3_PRIV_R_MASK_Pos  (9U)
#define SECU1_IRQ_CFG1_ILL_MPI3_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI3_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI3_PRIV_R_MASK  SECU1_IRQ_CFG1_ILL_MPI3_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI3_SEC_W_MASK_Pos  (10U)
#define SECU1_IRQ_CFG1_ILL_MPI3_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI3_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI3_SEC_W_MASK  SECU1_IRQ_CFG1_ILL_MPI3_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_MPI3_SEC_R_MASK_Pos  (11U)
#define SECU1_IRQ_CFG1_ILL_MPI3_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_MPI3_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_MPI3_SEC_R_MASK  SECU1_IRQ_CFG1_ILL_MPI3_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM0_PRIV_W_MASK_Pos  (12U)
#define SECU1_IRQ_CFG1_ILL_RAM0_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM0_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM0_PRIV_W_MASK  SECU1_IRQ_CFG1_ILL_RAM0_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM0_PRIV_R_MASK_Pos  (13U)
#define SECU1_IRQ_CFG1_ILL_RAM0_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM0_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM0_PRIV_R_MASK  SECU1_IRQ_CFG1_ILL_RAM0_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM0_SEC_W_MASK_Pos  (14U)
#define SECU1_IRQ_CFG1_ILL_RAM0_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM0_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM0_SEC_W_MASK  SECU1_IRQ_CFG1_ILL_RAM0_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM0_SEC_R_MASK_Pos  (15U)
#define SECU1_IRQ_CFG1_ILL_RAM0_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM0_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM0_SEC_R_MASK  SECU1_IRQ_CFG1_ILL_RAM0_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM1_PRIV_W_MASK_Pos  (16U)
#define SECU1_IRQ_CFG1_ILL_RAM1_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM1_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM1_PRIV_W_MASK  SECU1_IRQ_CFG1_ILL_RAM1_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM1_PRIV_R_MASK_Pos  (17U)
#define SECU1_IRQ_CFG1_ILL_RAM1_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM1_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM1_PRIV_R_MASK  SECU1_IRQ_CFG1_ILL_RAM1_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM1_SEC_W_MASK_Pos  (18U)
#define SECU1_IRQ_CFG1_ILL_RAM1_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM1_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM1_SEC_W_MASK  SECU1_IRQ_CFG1_ILL_RAM1_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM1_SEC_R_MASK_Pos  (19U)
#define SECU1_IRQ_CFG1_ILL_RAM1_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM1_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM1_SEC_R_MASK  SECU1_IRQ_CFG1_ILL_RAM1_SEC_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM2_PRIV_W_MASK_Pos  (20U)
#define SECU1_IRQ_CFG1_ILL_RAM2_PRIV_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM2_PRIV_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM2_PRIV_W_MASK  SECU1_IRQ_CFG1_ILL_RAM2_PRIV_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM2_PRIV_R_MASK_Pos  (21U)
#define SECU1_IRQ_CFG1_ILL_RAM2_PRIV_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM2_PRIV_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM2_PRIV_R_MASK  SECU1_IRQ_CFG1_ILL_RAM2_PRIV_R_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM2_SEC_W_MASK_Pos  (22U)
#define SECU1_IRQ_CFG1_ILL_RAM2_SEC_W_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM2_SEC_W_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM2_SEC_W_MASK  SECU1_IRQ_CFG1_ILL_RAM2_SEC_W_MASK_Msk
#define SECU1_IRQ_CFG1_ILL_RAM2_SEC_R_MASK_Pos  (23U)
#define SECU1_IRQ_CFG1_ILL_RAM2_SEC_R_MASK_Msk  (0x1UL << SECU1_IRQ_CFG1_ILL_RAM2_SEC_R_MASK_Pos)
#define SECU1_IRQ_CFG1_ILL_RAM2_SEC_R_MASK  SECU1_IRQ_CFG1_ILL_RAM2_SEC_R_MASK_Msk

/************** Bit definition for SECU1_HPMST_ATTR_CFG register **************/
#define SECU1_HPMST_ATTR_CFG_HCPU_SEC_Pos  (0U)
#define SECU1_HPMST_ATTR_CFG_HCPU_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_HCPU_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_HCPU_SEC   SECU1_HPMST_ATTR_CFG_HCPU_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_HCPU_SEC_USE_Pos  (1U)
#define SECU1_HPMST_ATTR_CFG_HCPU_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_HCPU_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_HCPU_SEC_USE  SECU1_HPMST_ATTR_CFG_HCPU_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_ACPU_SEC_Pos  (2U)
#define SECU1_HPMST_ATTR_CFG_ACPU_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_ACPU_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_ACPU_SEC   SECU1_HPMST_ATTR_CFG_ACPU_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_ACPU_SEC_USE_Pos  (3U)
#define SECU1_HPMST_ATTR_CFG_ACPU_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_ACPU_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_ACPU_SEC_USE  SECU1_HPMST_ATTR_CFG_ACPU_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_Pos  (4U)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_SEC  SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_Pos  (5U)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_Pos)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV  SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_Msk
#define SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_USE_Pos  (6U)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_USE  SECU1_HPMST_ATTR_CFG_EXTDMA_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_USE_Pos  (7U)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_USE  SECU1_HPMST_ATTR_CFG_EXTDMA_PRIV_USE_Msk
#define SECU1_HPMST_ATTR_CFG_EPIC_SEC_Pos  (8U)
#define SECU1_HPMST_ATTR_CFG_EPIC_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EPIC_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_EPIC_SEC   SECU1_HPMST_ATTR_CFG_EPIC_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_EPIC_PRIV_Pos  (9U)
#define SECU1_HPMST_ATTR_CFG_EPIC_PRIV_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EPIC_PRIV_Pos)
#define SECU1_HPMST_ATTR_CFG_EPIC_PRIV  SECU1_HPMST_ATTR_CFG_EPIC_PRIV_Msk
#define SECU1_HPMST_ATTR_CFG_EPIC_SEC_USE_Pos  (10U)
#define SECU1_HPMST_ATTR_CFG_EPIC_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EPIC_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_EPIC_SEC_USE  SECU1_HPMST_ATTR_CFG_EPIC_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_EPIC_PRIV_USE_Pos  (11U)
#define SECU1_HPMST_ATTR_CFG_EPIC_PRIV_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_EPIC_PRIV_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_EPIC_PRIV_USE  SECU1_HPMST_ATTR_CFG_EPIC_PRIV_USE_Msk
#define SECU1_HPMST_ATTR_CFG_LCDC_SEC_Pos  (12U)
#define SECU1_HPMST_ATTR_CFG_LCDC_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_LCDC_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_LCDC_SEC   SECU1_HPMST_ATTR_CFG_LCDC_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_LCDC_PRIV_Pos  (13U)
#define SECU1_HPMST_ATTR_CFG_LCDC_PRIV_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_LCDC_PRIV_Pos)
#define SECU1_HPMST_ATTR_CFG_LCDC_PRIV  SECU1_HPMST_ATTR_CFG_LCDC_PRIV_Msk
#define SECU1_HPMST_ATTR_CFG_LCDC_SEC_USE_Pos  (14U)
#define SECU1_HPMST_ATTR_CFG_LCDC_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_LCDC_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_LCDC_SEC_USE  SECU1_HPMST_ATTR_CFG_LCDC_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_LCDC_PRIV_USE_Pos  (15U)
#define SECU1_HPMST_ATTR_CFG_LCDC_PRIV_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_LCDC_PRIV_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_LCDC_PRIV_USE  SECU1_HPMST_ATTR_CFG_LCDC_PRIV_USE_Msk
#define SECU1_HPMST_ATTR_CFG_AES_SEC_Pos  (16U)
#define SECU1_HPMST_ATTR_CFG_AES_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_AES_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_AES_SEC    SECU1_HPMST_ATTR_CFG_AES_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_AES_PRIV_Pos  (17U)
#define SECU1_HPMST_ATTR_CFG_AES_PRIV_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_AES_PRIV_Pos)
#define SECU1_HPMST_ATTR_CFG_AES_PRIV   SECU1_HPMST_ATTR_CFG_AES_PRIV_Msk
#define SECU1_HPMST_ATTR_CFG_AES_SEC_USE_Pos  (18U)
#define SECU1_HPMST_ATTR_CFG_AES_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_AES_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_AES_SEC_USE  SECU1_HPMST_ATTR_CFG_AES_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_AES_PRIV_USE_Pos  (19U)
#define SECU1_HPMST_ATTR_CFG_AES_PRIV_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_AES_PRIV_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_AES_PRIV_USE  SECU1_HPMST_ATTR_CFG_AES_PRIV_USE_Msk
#define SECU1_HPMST_ATTR_CFG_USB_SEC_Pos  (20U)
#define SECU1_HPMST_ATTR_CFG_USB_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_USB_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_USB_SEC    SECU1_HPMST_ATTR_CFG_USB_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_USB_PRIV_Pos  (21U)
#define SECU1_HPMST_ATTR_CFG_USB_PRIV_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_USB_PRIV_Pos)
#define SECU1_HPMST_ATTR_CFG_USB_PRIV   SECU1_HPMST_ATTR_CFG_USB_PRIV_Msk
#define SECU1_HPMST_ATTR_CFG_USB_SEC_USE_Pos  (22U)
#define SECU1_HPMST_ATTR_CFG_USB_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_USB_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_USB_SEC_USE  SECU1_HPMST_ATTR_CFG_USB_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_USB_PRIV_USE_Pos  (23U)
#define SECU1_HPMST_ATTR_CFG_USB_PRIV_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_USB_PRIV_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_USB_PRIV_USE  SECU1_HPMST_ATTR_CFG_USB_PRIV_USE_Msk
#define SECU1_HPMST_ATTR_CFG_DMAC1_SEC_Pos  (24U)
#define SECU1_HPMST_ATTR_CFG_DMAC1_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_DMAC1_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_DMAC1_SEC  SECU1_HPMST_ATTR_CFG_DMAC1_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_Pos  (25U)
#define SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_Pos)
#define SECU1_HPMST_ATTR_CFG_DMAC1_PRIV  SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_Msk
#define SECU1_HPMST_ATTR_CFG_DMAC1_SEC_USE_Pos  (26U)
#define SECU1_HPMST_ATTR_CFG_DMAC1_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_DMAC1_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_DMAC1_SEC_USE  SECU1_HPMST_ATTR_CFG_DMAC1_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_USE_Pos  (27U)
#define SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_USE  SECU1_HPMST_ATTR_CFG_DMAC1_PRIV_USE_Msk
#define SECU1_HPMST_ATTR_CFG_PTC1_SEC_Pos  (28U)
#define SECU1_HPMST_ATTR_CFG_PTC1_SEC_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_PTC1_SEC_Pos)
#define SECU1_HPMST_ATTR_CFG_PTC1_SEC   SECU1_HPMST_ATTR_CFG_PTC1_SEC_Msk
#define SECU1_HPMST_ATTR_CFG_PTC1_PRIV_Pos  (29U)
#define SECU1_HPMST_ATTR_CFG_PTC1_PRIV_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_PTC1_PRIV_Pos)
#define SECU1_HPMST_ATTR_CFG_PTC1_PRIV  SECU1_HPMST_ATTR_CFG_PTC1_PRIV_Msk
#define SECU1_HPMST_ATTR_CFG_PTC1_SEC_USE_Pos  (30U)
#define SECU1_HPMST_ATTR_CFG_PTC1_SEC_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_PTC1_SEC_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_PTC1_SEC_USE  SECU1_HPMST_ATTR_CFG_PTC1_SEC_USE_Msk
#define SECU1_HPMST_ATTR_CFG_PTC1_PRIV_USE_Pos  (31U)
#define SECU1_HPMST_ATTR_CFG_PTC1_PRIV_USE_Msk  (0x1UL << SECU1_HPMST_ATTR_CFG_PTC1_PRIV_USE_Pos)
#define SECU1_HPMST_ATTR_CFG_PTC1_PRIV_USE  SECU1_HPMST_ATTR_CFG_PTC1_PRIV_USE_Msk

/************** Bit definition for SECU1_HPSLV_ATTR_CFG register **************/
#define SECU1_HPSLV_ATTR_CFG_DMAC1_SEC_Pos  (0U)
#define SECU1_HPSLV_ATTR_CFG_DMAC1_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_DMAC1_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_DMAC1_SEC  SECU1_HPSLV_ATTR_CFG_DMAC1_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_DMAC1_PRIV_Pos  (1U)
#define SECU1_HPSLV_ATTR_CFG_DMAC1_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_DMAC1_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_DMAC1_PRIV  SECU1_HPSLV_ATTR_CFG_DMAC1_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_AES_SEC_Pos  (2U)
#define SECU1_HPSLV_ATTR_CFG_AES_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_AES_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_AES_SEC    SECU1_HPSLV_ATTR_CFG_AES_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_AES_PRIV_Pos  (3U)
#define SECU1_HPSLV_ATTR_CFG_AES_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_AES_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_AES_PRIV   SECU1_HPSLV_ATTR_CFG_AES_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_EFUSE_SEC_Pos  (4U)
#define SECU1_HPSLV_ATTR_CFG_EFUSE_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_EFUSE_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_EFUSE_SEC  SECU1_HPSLV_ATTR_CFG_EFUSE_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_EFUSE_PRIV_Pos  (5U)
#define SECU1_HPSLV_ATTR_CFG_EFUSE_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_EFUSE_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_EFUSE_PRIV  SECU1_HPSLV_ATTR_CFG_EFUSE_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_TRNG_SEC_Pos  (6U)
#define SECU1_HPSLV_ATTR_CFG_TRNG_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_TRNG_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_TRNG_SEC   SECU1_HPSLV_ATTR_CFG_TRNG_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_TRNG_PRIV_Pos  (7U)
#define SECU1_HPSLV_ATTR_CFG_TRNG_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_TRNG_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_TRNG_PRIV  SECU1_HPSLV_ATTR_CFG_TRNG_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_PTC1_SEC_Pos  (8U)
#define SECU1_HPSLV_ATTR_CFG_PTC1_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_PTC1_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_PTC1_SEC   SECU1_HPSLV_ATTR_CFG_PTC1_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_PTC1_PRIV_Pos  (9U)
#define SECU1_HPSLV_ATTR_CFG_PTC1_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_PTC1_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_PTC1_PRIV  SECU1_HPSLV_ATTR_CFG_PTC1_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_SECU1_SEC_Pos  (10U)
#define SECU1_HPSLV_ATTR_CFG_SECU1_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_SECU1_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_SECU1_SEC  SECU1_HPSLV_ATTR_CFG_SECU1_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_SECU1_PRIV_Pos  (11U)
#define SECU1_HPSLV_ATTR_CFG_SECU1_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_SECU1_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_SECU1_PRIV  SECU1_HPSLV_ATTR_CFG_SECU1_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_ACPU_DBG_SEC_Pos  (12U)
#define SECU1_HPSLV_ATTR_CFG_ACPU_DBG_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_ACPU_DBG_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_ACPU_DBG_SEC  SECU1_HPSLV_ATTR_CFG_ACPU_DBG_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_ACPU_DBG_PRIV_Pos  (13U)
#define SECU1_HPSLV_ATTR_CFG_ACPU_DBG_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_ACPU_DBG_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_ACPU_DBG_PRIV  SECU1_HPSLV_ATTR_CFG_ACPU_DBG_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_HCPU_DBG_SEC_Pos  (14U)
#define SECU1_HPSLV_ATTR_CFG_HCPU_DBG_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_HCPU_DBG_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_HCPU_DBG_SEC  SECU1_HPSLV_ATTR_CFG_HCPU_DBG_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_HCPU_DBG_PRIV_Pos  (15U)
#define SECU1_HPSLV_ATTR_CFG_HCPU_DBG_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_HCPU_DBG_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_HCPU_DBG_PRIV  SECU1_HPSLV_ATTR_CFG_HCPU_DBG_PRIV_Msk
#define SECU1_HPSLV_ATTR_CFG_PERI2_SEC_Pos  (16U)
#define SECU1_HPSLV_ATTR_CFG_PERI2_SEC_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_PERI2_SEC_Pos)
#define SECU1_HPSLV_ATTR_CFG_PERI2_SEC  SECU1_HPSLV_ATTR_CFG_PERI2_SEC_Msk
#define SECU1_HPSLV_ATTR_CFG_PERI2_PRIV_Pos  (17U)
#define SECU1_HPSLV_ATTR_CFG_PERI2_PRIV_Msk  (0x1UL << SECU1_HPSLV_ATTR_CFG_PERI2_PRIV_Pos)
#define SECU1_HPSLV_ATTR_CFG_PERI2_PRIV  SECU1_HPSLV_ATTR_CFG_PERI2_PRIV_Msk

/*************** Bit definition for SECU1_MPI1_R0_CFG0 register ***************/
#define SECU1_MPI1_R0_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI1_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI1_R0_CFG0_ST_ADDR_Pos)
#define SECU1_MPI1_R0_CFG0_ST_ADDR      SECU1_MPI1_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI1_R0_CFG1 register ***************/
#define SECU1_MPI1_R0_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI1_R0_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI1_R0_CFG1_END_ADDR_Pos)
#define SECU1_MPI1_R0_CFG1_END_ADDR     SECU1_MPI1_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI1_R1_CFG0 register ***************/
#define SECU1_MPI1_R1_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI1_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI1_R1_CFG0_ST_ADDR_Pos)
#define SECU1_MPI1_R1_CFG0_ST_ADDR      SECU1_MPI1_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI1_R1_CFG1 register ***************/
#define SECU1_MPI1_R1_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI1_R1_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI1_R1_CFG1_END_ADDR_Pos)
#define SECU1_MPI1_R1_CFG1_END_ADDR     SECU1_MPI1_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI1_R2_CFG0 register ***************/
#define SECU1_MPI1_R2_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI1_R2_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI1_R2_CFG0_ST_ADDR_Pos)
#define SECU1_MPI1_R2_CFG0_ST_ADDR      SECU1_MPI1_R2_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI1_R2_CFG1 register ***************/
#define SECU1_MPI1_R2_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI1_R2_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI1_R2_CFG1_END_ADDR_Pos)
#define SECU1_MPI1_R2_CFG1_END_ADDR     SECU1_MPI1_R2_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI1_RW_CFG register ****************/
#define SECU1_MPI1_RW_CFG_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU1_MPI1_RW_CFG_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R0_PRIV_WR_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R0_PRIV_WR_ATTR  SECU1_MPI1_RW_CFG_R0_PRIV_WR_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU1_MPI1_RW_CFG_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R0_PRIV_RD_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R0_PRIV_RD_ATTR  SECU1_MPI1_RW_CFG_R0_PRIV_RD_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU1_MPI1_RW_CFG_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R0_SEC_WR_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R0_SEC_WR_ATTR  SECU1_MPI1_RW_CFG_R0_SEC_WR_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU1_MPI1_RW_CFG_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R0_SEC_RD_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R0_SEC_RD_ATTR  SECU1_MPI1_RW_CFG_R0_SEC_RD_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU1_MPI1_RW_CFG_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R1_PRIV_WR_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R1_PRIV_WR_ATTR  SECU1_MPI1_RW_CFG_R1_PRIV_WR_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU1_MPI1_RW_CFG_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R1_PRIV_RD_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R1_PRIV_RD_ATTR  SECU1_MPI1_RW_CFG_R1_PRIV_RD_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU1_MPI1_RW_CFG_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R1_SEC_WR_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R1_SEC_WR_ATTR  SECU1_MPI1_RW_CFG_R1_SEC_WR_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU1_MPI1_RW_CFG_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R1_SEC_RD_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R1_SEC_RD_ATTR  SECU1_MPI1_RW_CFG_R1_SEC_RD_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R2_PRIV_WR_ATTR_Pos  (8U)
#define SECU1_MPI1_RW_CFG_R2_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R2_PRIV_WR_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R2_PRIV_WR_ATTR  SECU1_MPI1_RW_CFG_R2_PRIV_WR_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R2_PRIV_RD_ATTR_Pos  (9U)
#define SECU1_MPI1_RW_CFG_R2_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R2_PRIV_RD_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R2_PRIV_RD_ATTR  SECU1_MPI1_RW_CFG_R2_PRIV_RD_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R2_SEC_WR_ATTR_Pos  (10U)
#define SECU1_MPI1_RW_CFG_R2_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R2_SEC_WR_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R2_SEC_WR_ATTR  SECU1_MPI1_RW_CFG_R2_SEC_WR_ATTR_Msk
#define SECU1_MPI1_RW_CFG_R2_SEC_RD_ATTR_Pos  (11U)
#define SECU1_MPI1_RW_CFG_R2_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI1_RW_CFG_R2_SEC_RD_ATTR_Pos)
#define SECU1_MPI1_RW_CFG_R2_SEC_RD_ATTR  SECU1_MPI1_RW_CFG_R2_SEC_RD_ATTR_Msk

/*************** Bit definition for SECU1_MPI2_R0_CFG0 register ***************/
#define SECU1_MPI2_R0_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI2_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI2_R0_CFG0_ST_ADDR_Pos)
#define SECU1_MPI2_R0_CFG0_ST_ADDR      SECU1_MPI2_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI2_R0_CFG1 register ***************/
#define SECU1_MPI2_R0_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI2_R0_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI2_R0_CFG1_END_ADDR_Pos)
#define SECU1_MPI2_R0_CFG1_END_ADDR     SECU1_MPI2_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI2_R1_CFG0 register ***************/
#define SECU1_MPI2_R1_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI2_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI2_R1_CFG0_ST_ADDR_Pos)
#define SECU1_MPI2_R1_CFG0_ST_ADDR      SECU1_MPI2_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI2_R1_CFG1 register ***************/
#define SECU1_MPI2_R1_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI2_R1_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI2_R1_CFG1_END_ADDR_Pos)
#define SECU1_MPI2_R1_CFG1_END_ADDR     SECU1_MPI2_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI2_R2_CFG0 register ***************/
#define SECU1_MPI2_R2_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI2_R2_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI2_R2_CFG0_ST_ADDR_Pos)
#define SECU1_MPI2_R2_CFG0_ST_ADDR      SECU1_MPI2_R2_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI2_R2_CFG1 register ***************/
#define SECU1_MPI2_R2_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI2_R2_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI2_R2_CFG1_END_ADDR_Pos)
#define SECU1_MPI2_R2_CFG1_END_ADDR     SECU1_MPI2_R2_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI2_RW_CFG register ****************/
#define SECU1_MPI2_RW_CFG_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU1_MPI2_RW_CFG_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R0_PRIV_WR_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R0_PRIV_WR_ATTR  SECU1_MPI2_RW_CFG_R0_PRIV_WR_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU1_MPI2_RW_CFG_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R0_PRIV_RD_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R0_PRIV_RD_ATTR  SECU1_MPI2_RW_CFG_R0_PRIV_RD_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU1_MPI2_RW_CFG_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R0_SEC_WR_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R0_SEC_WR_ATTR  SECU1_MPI2_RW_CFG_R0_SEC_WR_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU1_MPI2_RW_CFG_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R0_SEC_RD_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R0_SEC_RD_ATTR  SECU1_MPI2_RW_CFG_R0_SEC_RD_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU1_MPI2_RW_CFG_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R1_PRIV_WR_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R1_PRIV_WR_ATTR  SECU1_MPI2_RW_CFG_R1_PRIV_WR_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU1_MPI2_RW_CFG_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R1_PRIV_RD_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R1_PRIV_RD_ATTR  SECU1_MPI2_RW_CFG_R1_PRIV_RD_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU1_MPI2_RW_CFG_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R1_SEC_WR_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R1_SEC_WR_ATTR  SECU1_MPI2_RW_CFG_R1_SEC_WR_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU1_MPI2_RW_CFG_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R1_SEC_RD_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R1_SEC_RD_ATTR  SECU1_MPI2_RW_CFG_R1_SEC_RD_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R2_PRIV_WR_ATTR_Pos  (8U)
#define SECU1_MPI2_RW_CFG_R2_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R2_PRIV_WR_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R2_PRIV_WR_ATTR  SECU1_MPI2_RW_CFG_R2_PRIV_WR_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R2_PRIV_RD_ATTR_Pos  (9U)
#define SECU1_MPI2_RW_CFG_R2_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R2_PRIV_RD_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R2_PRIV_RD_ATTR  SECU1_MPI2_RW_CFG_R2_PRIV_RD_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R2_SEC_WR_ATTR_Pos  (10U)
#define SECU1_MPI2_RW_CFG_R2_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R2_SEC_WR_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R2_SEC_WR_ATTR  SECU1_MPI2_RW_CFG_R2_SEC_WR_ATTR_Msk
#define SECU1_MPI2_RW_CFG_R2_SEC_RD_ATTR_Pos  (11U)
#define SECU1_MPI2_RW_CFG_R2_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI2_RW_CFG_R2_SEC_RD_ATTR_Pos)
#define SECU1_MPI2_RW_CFG_R2_SEC_RD_ATTR  SECU1_MPI2_RW_CFG_R2_SEC_RD_ATTR_Msk

/*************** Bit definition for SECU1_MPI3_R0_CFG0 register ***************/
#define SECU1_MPI3_R0_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI3_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI3_R0_CFG0_ST_ADDR_Pos)
#define SECU1_MPI3_R0_CFG0_ST_ADDR      SECU1_MPI3_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI3_R0_CFG1 register ***************/
#define SECU1_MPI3_R0_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI3_R0_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI3_R0_CFG1_END_ADDR_Pos)
#define SECU1_MPI3_R0_CFG1_END_ADDR     SECU1_MPI3_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI3_R1_CFG0 register ***************/
#define SECU1_MPI3_R1_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI3_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI3_R1_CFG0_ST_ADDR_Pos)
#define SECU1_MPI3_R1_CFG0_ST_ADDR      SECU1_MPI3_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI3_R1_CFG1 register ***************/
#define SECU1_MPI3_R1_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI3_R1_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI3_R1_CFG1_END_ADDR_Pos)
#define SECU1_MPI3_R1_CFG1_END_ADDR     SECU1_MPI3_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI3_R2_CFG0 register ***************/
#define SECU1_MPI3_R2_CFG0_ST_ADDR_Pos  (10U)
#define SECU1_MPI3_R2_CFG0_ST_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI3_R2_CFG0_ST_ADDR_Pos)
#define SECU1_MPI3_R2_CFG0_ST_ADDR      SECU1_MPI3_R2_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_MPI3_R2_CFG1 register ***************/
#define SECU1_MPI3_R2_CFG1_END_ADDR_Pos  (10U)
#define SECU1_MPI3_R2_CFG1_END_ADDR_Msk  (0x3FFFFFUL << SECU1_MPI3_R2_CFG1_END_ADDR_Pos)
#define SECU1_MPI3_R2_CFG1_END_ADDR     SECU1_MPI3_R2_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_MPI3_RW_CFG register ****************/
#define SECU1_MPI3_RW_CFG_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU1_MPI3_RW_CFG_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R0_PRIV_WR_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R0_PRIV_WR_ATTR  SECU1_MPI3_RW_CFG_R0_PRIV_WR_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU1_MPI3_RW_CFG_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R0_PRIV_RD_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R0_PRIV_RD_ATTR  SECU1_MPI3_RW_CFG_R0_PRIV_RD_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU1_MPI3_RW_CFG_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R0_SEC_WR_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R0_SEC_WR_ATTR  SECU1_MPI3_RW_CFG_R0_SEC_WR_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU1_MPI3_RW_CFG_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R0_SEC_RD_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R0_SEC_RD_ATTR  SECU1_MPI3_RW_CFG_R0_SEC_RD_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU1_MPI3_RW_CFG_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R1_PRIV_WR_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R1_PRIV_WR_ATTR  SECU1_MPI3_RW_CFG_R1_PRIV_WR_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU1_MPI3_RW_CFG_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R1_PRIV_RD_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R1_PRIV_RD_ATTR  SECU1_MPI3_RW_CFG_R1_PRIV_RD_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU1_MPI3_RW_CFG_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R1_SEC_WR_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R1_SEC_WR_ATTR  SECU1_MPI3_RW_CFG_R1_SEC_WR_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU1_MPI3_RW_CFG_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R1_SEC_RD_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R1_SEC_RD_ATTR  SECU1_MPI3_RW_CFG_R1_SEC_RD_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R2_PRIV_WR_ATTR_Pos  (8U)
#define SECU1_MPI3_RW_CFG_R2_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R2_PRIV_WR_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R2_PRIV_WR_ATTR  SECU1_MPI3_RW_CFG_R2_PRIV_WR_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R2_PRIV_RD_ATTR_Pos  (9U)
#define SECU1_MPI3_RW_CFG_R2_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R2_PRIV_RD_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R2_PRIV_RD_ATTR  SECU1_MPI3_RW_CFG_R2_PRIV_RD_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R2_SEC_WR_ATTR_Pos  (10U)
#define SECU1_MPI3_RW_CFG_R2_SEC_WR_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R2_SEC_WR_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R2_SEC_WR_ATTR  SECU1_MPI3_RW_CFG_R2_SEC_WR_ATTR_Msk
#define SECU1_MPI3_RW_CFG_R2_SEC_RD_ATTR_Pos  (11U)
#define SECU1_MPI3_RW_CFG_R2_SEC_RD_ATTR_Msk  (0x1UL << SECU1_MPI3_RW_CFG_R2_SEC_RD_ATTR_Pos)
#define SECU1_MPI3_RW_CFG_R2_SEC_RD_ATTR  SECU1_MPI3_RW_CFG_R2_SEC_RD_ATTR_Msk

/*************** Bit definition for SECU1_RAM0_R0_CFG0 register ***************/
#define SECU1_RAM0_R0_CFG0_ST_ADDR_Pos  (2U)
#define SECU1_RAM0_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM0_R0_CFG0_ST_ADDR_Pos)
#define SECU1_RAM0_R0_CFG0_ST_ADDR      SECU1_RAM0_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_RAM0_R0_CFG1 register ***************/
#define SECU1_RAM0_R0_CFG1_END_ADDR_Pos  (2U)
#define SECU1_RAM0_R0_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM0_R0_CFG1_END_ADDR_Pos)
#define SECU1_RAM0_R0_CFG1_END_ADDR     SECU1_RAM0_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_RAM0_R1_CFG0 register ***************/
#define SECU1_RAM0_R1_CFG0_ST_ADDR_Pos  (2U)
#define SECU1_RAM0_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM0_R1_CFG0_ST_ADDR_Pos)
#define SECU1_RAM0_R1_CFG0_ST_ADDR      SECU1_RAM0_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_RAM0_R1_CFG1 register ***************/
#define SECU1_RAM0_R1_CFG1_END_ADDR_Pos  (2U)
#define SECU1_RAM0_R1_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM0_R1_CFG1_END_ADDR_Pos)
#define SECU1_RAM0_R1_CFG1_END_ADDR     SECU1_RAM0_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_RAM0_RW_ATTR register ***************/
#define SECU1_RAM0_RW_ATTR_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU1_RAM0_RW_ATTR_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R0_PRIV_WR_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R0_PRIV_WR_ATTR  SECU1_RAM0_RW_ATTR_R0_PRIV_WR_ATTR_Msk
#define SECU1_RAM0_RW_ATTR_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU1_RAM0_RW_ATTR_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R0_PRIV_RD_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R0_PRIV_RD_ATTR  SECU1_RAM0_RW_ATTR_R0_PRIV_RD_ATTR_Msk
#define SECU1_RAM0_RW_ATTR_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU1_RAM0_RW_ATTR_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R0_SEC_WR_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R0_SEC_WR_ATTR  SECU1_RAM0_RW_ATTR_R0_SEC_WR_ATTR_Msk
#define SECU1_RAM0_RW_ATTR_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU1_RAM0_RW_ATTR_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R0_SEC_RD_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R0_SEC_RD_ATTR  SECU1_RAM0_RW_ATTR_R0_SEC_RD_ATTR_Msk
#define SECU1_RAM0_RW_ATTR_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU1_RAM0_RW_ATTR_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R1_PRIV_WR_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R1_PRIV_WR_ATTR  SECU1_RAM0_RW_ATTR_R1_PRIV_WR_ATTR_Msk
#define SECU1_RAM0_RW_ATTR_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU1_RAM0_RW_ATTR_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R1_PRIV_RD_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R1_PRIV_RD_ATTR  SECU1_RAM0_RW_ATTR_R1_PRIV_RD_ATTR_Msk
#define SECU1_RAM0_RW_ATTR_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU1_RAM0_RW_ATTR_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R1_SEC_WR_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R1_SEC_WR_ATTR  SECU1_RAM0_RW_ATTR_R1_SEC_WR_ATTR_Msk
#define SECU1_RAM0_RW_ATTR_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU1_RAM0_RW_ATTR_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU1_RAM0_RW_ATTR_R1_SEC_RD_ATTR_Pos)
#define SECU1_RAM0_RW_ATTR_R1_SEC_RD_ATTR  SECU1_RAM0_RW_ATTR_R1_SEC_RD_ATTR_Msk

/*************** Bit definition for SECU1_RAM1_R0_CFG0 register ***************/
#define SECU1_RAM1_R0_CFG0_ST_ADDR_Pos  (2U)
#define SECU1_RAM1_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM1_R0_CFG0_ST_ADDR_Pos)
#define SECU1_RAM1_R0_CFG0_ST_ADDR      SECU1_RAM1_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_RAM1_R0_CFG1 register ***************/
#define SECU1_RAM1_R0_CFG1_END_ADDR_Pos  (2U)
#define SECU1_RAM1_R0_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM1_R0_CFG1_END_ADDR_Pos)
#define SECU1_RAM1_R0_CFG1_END_ADDR     SECU1_RAM1_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_RAM1_R1_CFG0 register ***************/
#define SECU1_RAM1_R1_CFG0_ST_ADDR_Pos  (2U)
#define SECU1_RAM1_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM1_R1_CFG0_ST_ADDR_Pos)
#define SECU1_RAM1_R1_CFG0_ST_ADDR      SECU1_RAM1_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_RAM1_R1_CFG1 register ***************/
#define SECU1_RAM1_R1_CFG1_END_ADDR_Pos  (2U)
#define SECU1_RAM1_R1_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM1_R1_CFG1_END_ADDR_Pos)
#define SECU1_RAM1_R1_CFG1_END_ADDR     SECU1_RAM1_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_RAM1_RW_ATTR register ***************/
#define SECU1_RAM1_RW_ATTR_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU1_RAM1_RW_ATTR_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R0_PRIV_WR_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R0_PRIV_WR_ATTR  SECU1_RAM1_RW_ATTR_R0_PRIV_WR_ATTR_Msk
#define SECU1_RAM1_RW_ATTR_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU1_RAM1_RW_ATTR_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R0_PRIV_RD_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R0_PRIV_RD_ATTR  SECU1_RAM1_RW_ATTR_R0_PRIV_RD_ATTR_Msk
#define SECU1_RAM1_RW_ATTR_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU1_RAM1_RW_ATTR_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R0_SEC_WR_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R0_SEC_WR_ATTR  SECU1_RAM1_RW_ATTR_R0_SEC_WR_ATTR_Msk
#define SECU1_RAM1_RW_ATTR_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU1_RAM1_RW_ATTR_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R0_SEC_RD_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R0_SEC_RD_ATTR  SECU1_RAM1_RW_ATTR_R0_SEC_RD_ATTR_Msk
#define SECU1_RAM1_RW_ATTR_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU1_RAM1_RW_ATTR_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R1_PRIV_WR_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R1_PRIV_WR_ATTR  SECU1_RAM1_RW_ATTR_R1_PRIV_WR_ATTR_Msk
#define SECU1_RAM1_RW_ATTR_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU1_RAM1_RW_ATTR_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R1_PRIV_RD_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R1_PRIV_RD_ATTR  SECU1_RAM1_RW_ATTR_R1_PRIV_RD_ATTR_Msk
#define SECU1_RAM1_RW_ATTR_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU1_RAM1_RW_ATTR_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R1_SEC_WR_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R1_SEC_WR_ATTR  SECU1_RAM1_RW_ATTR_R1_SEC_WR_ATTR_Msk
#define SECU1_RAM1_RW_ATTR_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU1_RAM1_RW_ATTR_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU1_RAM1_RW_ATTR_R1_SEC_RD_ATTR_Pos)
#define SECU1_RAM1_RW_ATTR_R1_SEC_RD_ATTR  SECU1_RAM1_RW_ATTR_R1_SEC_RD_ATTR_Msk

/*************** Bit definition for SECU1_RAM2_R0_CFG0 register ***************/
#define SECU1_RAM2_R0_CFG0_ST_ADDR_Pos  (2U)
#define SECU1_RAM2_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM2_R0_CFG0_ST_ADDR_Pos)
#define SECU1_RAM2_R0_CFG0_ST_ADDR      SECU1_RAM2_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_RAM2_R0_CFG1 register ***************/
#define SECU1_RAM2_R0_CFG1_END_ADDR_Pos  (2U)
#define SECU1_RAM2_R0_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM2_R0_CFG1_END_ADDR_Pos)
#define SECU1_RAM2_R0_CFG1_END_ADDR     SECU1_RAM2_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_RAM2_R1_CFG0 register ***************/
#define SECU1_RAM2_R1_CFG0_ST_ADDR_Pos  (2U)
#define SECU1_RAM2_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM2_R1_CFG0_ST_ADDR_Pos)
#define SECU1_RAM2_R1_CFG0_ST_ADDR      SECU1_RAM2_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU1_RAM2_R1_CFG1 register ***************/
#define SECU1_RAM2_R1_CFG1_END_ADDR_Pos  (2U)
#define SECU1_RAM2_R1_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU1_RAM2_R1_CFG1_END_ADDR_Pos)
#define SECU1_RAM2_R1_CFG1_END_ADDR     SECU1_RAM2_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU1_RAM2_RW_ATTR register ***************/
#define SECU1_RAM2_RW_ATTR_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU1_RAM2_RW_ATTR_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R0_PRIV_WR_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R0_PRIV_WR_ATTR  SECU1_RAM2_RW_ATTR_R0_PRIV_WR_ATTR_Msk
#define SECU1_RAM2_RW_ATTR_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU1_RAM2_RW_ATTR_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R0_PRIV_RD_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R0_PRIV_RD_ATTR  SECU1_RAM2_RW_ATTR_R0_PRIV_RD_ATTR_Msk
#define SECU1_RAM2_RW_ATTR_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU1_RAM2_RW_ATTR_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R0_SEC_WR_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R0_SEC_WR_ATTR  SECU1_RAM2_RW_ATTR_R0_SEC_WR_ATTR_Msk
#define SECU1_RAM2_RW_ATTR_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU1_RAM2_RW_ATTR_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R0_SEC_RD_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R0_SEC_RD_ATTR  SECU1_RAM2_RW_ATTR_R0_SEC_RD_ATTR_Msk
#define SECU1_RAM2_RW_ATTR_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU1_RAM2_RW_ATTR_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R1_PRIV_WR_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R1_PRIV_WR_ATTR  SECU1_RAM2_RW_ATTR_R1_PRIV_WR_ATTR_Msk
#define SECU1_RAM2_RW_ATTR_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU1_RAM2_RW_ATTR_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R1_PRIV_RD_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R1_PRIV_RD_ATTR  SECU1_RAM2_RW_ATTR_R1_PRIV_RD_ATTR_Msk
#define SECU1_RAM2_RW_ATTR_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU1_RAM2_RW_ATTR_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R1_SEC_WR_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R1_SEC_WR_ATTR  SECU1_RAM2_RW_ATTR_R1_SEC_WR_ATTR_Msk
#define SECU1_RAM2_RW_ATTR_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU1_RAM2_RW_ATTR_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU1_RAM2_RW_ATTR_R1_SEC_RD_ATTR_Pos)
#define SECU1_RAM2_RW_ATTR_R1_SEC_RD_ATTR  SECU1_RAM2_RW_ATTR_R1_SEC_RD_ATTR_Msk

/******************* Bit definition for SECU1_ACPU register *******************/
#define SECU1_ACPU_WAIT_Pos             (0U)
#define SECU1_ACPU_WAIT_Msk             (0x1UL << SECU1_ACPU_WAIT_Pos)
#define SECU1_ACPU_WAIT                 SECU1_ACPU_WAIT_Msk
#define SECU1_ACPU_LOCKNSVTOR_Pos       (1U)
#define SECU1_ACPU_LOCKNSVTOR_Msk       (0x1UL << SECU1_ACPU_LOCKNSVTOR_Pos)
#define SECU1_ACPU_LOCKNSVTOR           SECU1_ACPU_LOCKNSVTOR_Msk
#define SECU1_ACPU_LOCKNSMPU_Pos        (2U)
#define SECU1_ACPU_LOCKNSMPU_Msk        (0x1UL << SECU1_ACPU_LOCKNSMPU_Pos)
#define SECU1_ACPU_LOCKNSMPU            SECU1_ACPU_LOCKNSMPU_Msk
#define SECU1_ACPU_RSTR_Pos             (3U)
#define SECU1_ACPU_RSTR_Msk             (0x1UL << SECU1_ACPU_RSTR_Pos)
#define SECU1_ACPU_RSTR                 SECU1_ACPU_RSTR_Msk
#define SECU1_ACPU_ENR_Pos              (4U)
#define SECU1_ACPU_ENR_Msk              (0x1UL << SECU1_ACPU_ENR_Pos)
#define SECU1_ACPU_ENR                  SECU1_ACPU_ENR_Msk
#define SECU1_ACPU_VTOR_Pos             (7U)
#define SECU1_ACPU_VTOR_Msk             (0x1FFFFFFUL << SECU1_ACPU_VTOR_Pos)
#define SECU1_ACPU_VTOR                 SECU1_ACPU_VTOR_Msk

/******************* Bit definition for SECU1_MISC register *******************/
#define SECU1_MISC_AES_RK_LOCK_Pos      (0U)
#define SECU1_MISC_AES_RK_LOCK_Msk      (0x1UL << SECU1_MISC_AES_RK_LOCK_Pos)
#define SECU1_MISC_AES_RK_LOCK          SECU1_MISC_AES_RK_LOCK_Msk
#define SECU1_MISC_LOCKNSVTOR_Pos       (1U)
#define SECU1_MISC_LOCKNSVTOR_Msk       (0x1UL << SECU1_MISC_LOCKNSVTOR_Pos)
#define SECU1_MISC_LOCKNSVTOR           SECU1_MISC_LOCKNSVTOR_Msk
#define SECU1_MISC_LOCKNSMPU_Pos        (2U)
#define SECU1_MISC_LOCKNSMPU_Msk        (0x1UL << SECU1_MISC_LOCKNSMPU_Pos)
#define SECU1_MISC_LOCKNSMPU            SECU1_MISC_LOCKNSMPU_Msk

/**************** Bit definition for SECU1_DBG_CODE0 register *****************/
#define SECU1_DBG_CODE0_DATA_Pos        (0U)
#define SECU1_DBG_CODE0_DATA_Msk        (0xFFFFFFFFUL << SECU1_DBG_CODE0_DATA_Pos)
#define SECU1_DBG_CODE0_DATA            SECU1_DBG_CODE0_DATA_Msk

/**************** Bit definition for SECU1_DBG_CODE1 register *****************/
#define SECU1_DBG_CODE1_DATA_Pos        (0U)
#define SECU1_DBG_CODE1_DATA_Msk        (0xFFFFFFFFUL << SECU1_DBG_CODE1_DATA_Pos)
#define SECU1_DBG_CODE1_DATA            SECU1_DBG_CODE1_DATA_Msk

/**************** Bit definition for SECU1_DBG_CODE2 register *****************/
#define SECU1_DBG_CODE2_DATA_Pos        (0U)
#define SECU1_DBG_CODE2_DATA_Msk        (0xFFFFFFFFUL << SECU1_DBG_CODE2_DATA_Pos)
#define SECU1_DBG_CODE2_DATA            SECU1_DBG_CODE2_DATA_Msk

/**************** Bit definition for SECU1_DBG_CODE3 register *****************/
#define SECU1_DBG_CODE3_DATA_Pos        (0U)
#define SECU1_DBG_CODE3_DATA_Msk        (0xFFFFFFFFUL << SECU1_DBG_CODE3_DATA_Pos)
#define SECU1_DBG_CODE3_DATA            SECU1_DBG_CODE3_DATA_Msk

/*************** Bit definition for SECU1_AHB_ACC_CFG register ****************/
#define SECU1_AHB_ACC_CFG_SEC_ATTR_Pos  (0U)
#define SECU1_AHB_ACC_CFG_SEC_ATTR_Msk  (0xFFFFUL << SECU1_AHB_ACC_CFG_SEC_ATTR_Pos)
#define SECU1_AHB_ACC_CFG_SEC_ATTR      SECU1_AHB_ACC_CFG_SEC_ATTR_Msk
#define SECU1_AHB_ACC_CFG_PRIV_ATTR_Pos  (16U)
#define SECU1_AHB_ACC_CFG_PRIV_ATTR_Msk  (0xFFFFUL << SECU1_AHB_ACC_CFG_PRIV_ATTR_Pos)
#define SECU1_AHB_ACC_CFG_PRIV_ATTR     SECU1_AHB_ACC_CFG_PRIV_ATTR_Msk

/*************** Bit definition for SECU1_APB1_ACC_CFG register ***************/
#define SECU1_APB1_ACC_CFG_SEC_ATTR_Pos  (0U)
#define SECU1_APB1_ACC_CFG_SEC_ATTR_Msk  (0xFFFFUL << SECU1_APB1_ACC_CFG_SEC_ATTR_Pos)
#define SECU1_APB1_ACC_CFG_SEC_ATTR     SECU1_APB1_ACC_CFG_SEC_ATTR_Msk
#define SECU1_APB1_ACC_CFG_PRIV_ATTR_Pos  (16U)
#define SECU1_APB1_ACC_CFG_PRIV_ATTR_Msk  (0xFFFFUL << SECU1_APB1_ACC_CFG_PRIV_ATTR_Pos)
#define SECU1_APB1_ACC_CFG_PRIV_ATTR    SECU1_APB1_ACC_CFG_PRIV_ATTR_Msk

/*************** Bit definition for SECU1_APB2_ACC_CFG register ***************/
#define SECU1_APB2_ACC_CFG_SEC_ATTR_Pos  (0U)
#define SECU1_APB2_ACC_CFG_SEC_ATTR_Msk  (0xFFFFUL << SECU1_APB2_ACC_CFG_SEC_ATTR_Pos)
#define SECU1_APB2_ACC_CFG_SEC_ATTR     SECU1_APB2_ACC_CFG_SEC_ATTR_Msk
#define SECU1_APB2_ACC_CFG_PRIV_ATTR_Pos  (16U)
#define SECU1_APB2_ACC_CFG_PRIV_ATTR_Msk  (0xFFFFUL << SECU1_APB2_ACC_CFG_PRIV_ATTR_Pos)
#define SECU1_APB2_ACC_CFG_PRIV_ATTR    SECU1_APB2_ACC_CFG_PRIV_ATTR_Msk

/*************** Bit definition for SECU1_APB3_ACC_CFG register ***************/
#define SECU1_APB3_ACC_CFG_SEC_ATTR_Pos  (0U)
#define SECU1_APB3_ACC_CFG_SEC_ATTR_Msk  (0xFFFFUL << SECU1_APB3_ACC_CFG_SEC_ATTR_Pos)
#define SECU1_APB3_ACC_CFG_SEC_ATTR     SECU1_APB3_ACC_CFG_SEC_ATTR_Msk
#define SECU1_APB3_ACC_CFG_PRIV_ATTR_Pos  (16U)
#define SECU1_APB3_ACC_CFG_PRIV_ATTR_Msk  (0xFFFFUL << SECU1_APB3_ACC_CFG_PRIV_ATTR_Pos)
#define SECU1_APB3_ACC_CFG_PRIV_ATTR    SECU1_APB3_ACC_CFG_PRIV_ATTR_Msk

/*************** Bit definition for SECU1_APB4_ACC_CFG register ***************/
#define SECU1_APB4_ACC_CFG_SEC_ATTR_Pos  (0U)
#define SECU1_APB4_ACC_CFG_SEC_ATTR_Msk  (0xFFFFUL << SECU1_APB4_ACC_CFG_SEC_ATTR_Pos)
#define SECU1_APB4_ACC_CFG_SEC_ATTR     SECU1_APB4_ACC_CFG_SEC_ATTR_Msk
#define SECU1_APB4_ACC_CFG_PRIV_ATTR_Pos  (16U)
#define SECU1_APB4_ACC_CFG_PRIV_ATTR_Msk  (0xFFFFUL << SECU1_APB4_ACC_CFG_PRIV_ATTR_Pos)
#define SECU1_APB4_ACC_CFG_PRIV_ATTR    SECU1_APB4_ACC_CFG_PRIV_ATTR_Msk

#endif
