/*
 * SPDX-FileCopyrightText: 2025 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __TSEN_H
#define __TSEN_H

typedef struct
{
    __IO uint32_t TSEN_CTRL_REG;
    __IO uint32_t TSEN_HW_SAMP_CTRL;
    __IO uint32_t TSEN_IRQ_THD;
    __IO uint32_t TSEN_RDATA;
    __IO uint32_t TSEN_IRQ;
} TSEN_TypeDef;


/*************** Bit definition for TSEN_TSEN_CTRL_REG register ***************/
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_PU_Pos  (0U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_PU_Msk  (0x1UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_PU_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_PU  TSEN_TSEN_CTRL_REG_ANAU_TSEN_PU_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RSTB_Pos  (1U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RSTB_Msk  (0x1UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_RSTB_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RSTB  TSEN_TSEN_CTRL_REG_ANAU_TSEN_RSTB_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RUN_Pos  (2U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RUN_Msk  (0x1UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_RUN_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RUN  TSEN_TSEN_CTRL_REG_ANAU_TSEN_RUN_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_IG_VBE_Pos  (3U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_IG_VBE_Msk  (0x7UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_IG_VBE_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_IG_VBE  TSEN_TSEN_CTRL_REG_ANAU_TSEN_IG_VBE_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_FCK_SEL_Pos  (6U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_FCK_SEL_Msk  (0x3UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_FCK_SEL_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_FCK_SEL  TSEN_TSEN_CTRL_REG_ANAU_TSEN_FCK_SEL_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_SGN_EN_Pos  (8U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_SGN_EN_Msk  (0x1UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_SGN_EN_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_SGN_EN  TSEN_TSEN_CTRL_REG_ANAU_TSEN_SGN_EN_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_SER_PAR_SEL_Pos  (9U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_SER_PAR_SEL_Msk  (0x1UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_SER_PAR_SEL_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_SER_PAR_SEL  TSEN_TSEN_CTRL_REG_ANAU_TSEN_SER_PAR_SEL_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RDY_Pos  (10U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RDY_Msk  (0x1UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_RDY_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_RDY  TSEN_TSEN_CTRL_REG_ANAU_TSEN_RDY_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_EN_Pos  (11U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_EN_Msk  (0x1UL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_EN_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_EN  TSEN_TSEN_CTRL_REG_ANAU_TSEN_EN_Msk
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_CLK_DIV_Pos  (12U)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_CLK_DIV_Msk  (0x3FUL << TSEN_TSEN_CTRL_REG_ANAU_TSEN_CLK_DIV_Pos)
#define TSEN_TSEN_CTRL_REG_ANAU_TSEN_CLK_DIV  TSEN_TSEN_CTRL_REG_ANAU_TSEN_CLK_DIV_Msk

/************* Bit definition for TSEN_TSEN_HW_SAMP_CTRL register *************/
#define TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_EN_Pos  (0U)
#define TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_EN_Msk  (0x1UL << TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_EN_Pos)
#define TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_EN  TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_EN_Msk
#define TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_TRIG_Pos  (1U)
#define TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_TRIG_Msk  (0x1UL << TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_TRIG_Pos)
#define TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_TRIG  TSEN_TSEN_HW_SAMP_CTRL_HW_SAMP_TRIG_Msk
#define TSEN_TSEN_HW_SAMP_CTRL_PU_INTVL_Pos  (4U)
#define TSEN_TSEN_HW_SAMP_CTRL_PU_INTVL_Msk  (0xFUL << TSEN_TSEN_HW_SAMP_CTRL_PU_INTVL_Pos)
#define TSEN_TSEN_HW_SAMP_CTRL_PU_INTVL  TSEN_TSEN_HW_SAMP_CTRL_PU_INTVL_Msk
#define TSEN_TSEN_HW_SAMP_CTRL_RSTB_WIDTH_Pos  (8U)
#define TSEN_TSEN_HW_SAMP_CTRL_RSTB_WIDTH_Msk  (0x1FUL << TSEN_TSEN_HW_SAMP_CTRL_RSTB_WIDTH_Pos)
#define TSEN_TSEN_HW_SAMP_CTRL_RSTB_WIDTH  TSEN_TSEN_HW_SAMP_CTRL_RSTB_WIDTH_Msk
#define TSEN_TSEN_HW_SAMP_CTRL_RSTB_INTVL_Pos  (16U)
#define TSEN_TSEN_HW_SAMP_CTRL_RSTB_INTVL_Msk  (0x1FUL << TSEN_TSEN_HW_SAMP_CTRL_RSTB_INTVL_Pos)
#define TSEN_TSEN_HW_SAMP_CTRL_RSTB_INTVL  TSEN_TSEN_HW_SAMP_CTRL_RSTB_INTVL_Msk

/*************** Bit definition for TSEN_TSEN_IRQ_THD register ****************/
#define TSEN_TSEN_IRQ_THD_TSEN_THD_L_Pos  (0U)
#define TSEN_TSEN_IRQ_THD_TSEN_THD_L_Msk  (0xFFFUL << TSEN_TSEN_IRQ_THD_TSEN_THD_L_Pos)
#define TSEN_TSEN_IRQ_THD_TSEN_THD_L    TSEN_TSEN_IRQ_THD_TSEN_THD_L_Msk
#define TSEN_TSEN_IRQ_THD_TSEN_THD_H_Pos  (16U)
#define TSEN_TSEN_IRQ_THD_TSEN_THD_H_Msk  (0xFFFUL << TSEN_TSEN_IRQ_THD_TSEN_THD_H_Pos)
#define TSEN_TSEN_IRQ_THD_TSEN_THD_H    TSEN_TSEN_IRQ_THD_TSEN_THD_H_Msk

/**************** Bit definition for TSEN_TSEN_RDATA register *****************/
#define TSEN_TSEN_RDATA_TSEN_RDATA_Pos  (0U)
#define TSEN_TSEN_RDATA_TSEN_RDATA_Msk  (0xFFFUL << TSEN_TSEN_RDATA_TSEN_RDATA_Pos)
#define TSEN_TSEN_RDATA_TSEN_RDATA      TSEN_TSEN_RDATA_TSEN_RDATA_Msk

/***************** Bit definition for TSEN_TSEN_IRQ register ******************/
#define TSEN_TSEN_IRQ_TSEN_ICR_0_Pos    (0U)
#define TSEN_TSEN_IRQ_TSEN_ICR_0_Msk    (0x1UL << TSEN_TSEN_IRQ_TSEN_ICR_0_Pos)
#define TSEN_TSEN_IRQ_TSEN_ICR_0        TSEN_TSEN_IRQ_TSEN_ICR_0_Msk
#define TSEN_TSEN_IRQ_TSEN_ICR_1_Pos    (1U)
#define TSEN_TSEN_IRQ_TSEN_ICR_1_Msk    (0x1UL << TSEN_TSEN_IRQ_TSEN_ICR_1_Pos)
#define TSEN_TSEN_IRQ_TSEN_ICR_1        TSEN_TSEN_IRQ_TSEN_ICR_1_Msk
#define TSEN_TSEN_IRQ_TSEN_ICR_2_Pos    (2U)
#define TSEN_TSEN_IRQ_TSEN_ICR_2_Msk    (0x1UL << TSEN_TSEN_IRQ_TSEN_ICR_2_Pos)
#define TSEN_TSEN_IRQ_TSEN_ICR_2        TSEN_TSEN_IRQ_TSEN_ICR_2_Msk
#define TSEN_TSEN_IRQ_TSEN_IMR_Pos      (4U)
#define TSEN_TSEN_IRQ_TSEN_IMR_Msk      (0x7UL << TSEN_TSEN_IRQ_TSEN_IMR_Pos)
#define TSEN_TSEN_IRQ_TSEN_IMR          TSEN_TSEN_IRQ_TSEN_IMR_Msk
#define TSEN_TSEN_IRQ_TSEN_IRSR_Pos     (8U)
#define TSEN_TSEN_IRQ_TSEN_IRSR_Msk     (0x7UL << TSEN_TSEN_IRQ_TSEN_IRSR_Pos)
#define TSEN_TSEN_IRQ_TSEN_IRSR         TSEN_TSEN_IRQ_TSEN_IRSR_Msk
#define TSEN_TSEN_IRQ_TSEN_ISR_Pos      (12U)
#define TSEN_TSEN_IRQ_TSEN_ISR_Msk      (0x7UL << TSEN_TSEN_IRQ_TSEN_ISR_Pos)
#define TSEN_TSEN_IRQ_TSEN_ISR          TSEN_TSEN_IRQ_TSEN_ISR_Msk
#define TSEN_TSEN_IRQ_TSEN_PTC_IMR_Pos  (16U)
#define TSEN_TSEN_IRQ_TSEN_PTC_IMR_Msk  (0x7UL << TSEN_TSEN_IRQ_TSEN_PTC_IMR_Pos)
#define TSEN_TSEN_IRQ_TSEN_PTC_IMR      TSEN_TSEN_IRQ_TSEN_PTC_IMR_Msk
#define TSEN_TSEN_IRQ_TSEN_BUSY_Pos     (31U)
#define TSEN_TSEN_IRQ_TSEN_BUSY_Msk     (0x1UL << TSEN_TSEN_IRQ_TSEN_BUSY_Pos)
#define TSEN_TSEN_IRQ_TSEN_BUSY         TSEN_TSEN_IRQ_TSEN_BUSY_Msk


#endif