import os
from building import * 

# get current dir path
cwd = GetCurrentDir()
reg_fwk = os.path.join(cwd, 'reg_fwk')

# init src and inc vars
src = []
inc = [cwd, reg_fwk]


# add driver basic code
src = src + Glob('./*.c')
src = src + Glob('./reg_fwk/*.c')

if GetDepend("DISABLE_LVGL_V8") and GetDepend("DISABLE_LVGL_V9"):
    src = src + Glob('./lvgl_v7/*.c')
elif GetDepend("DISABLE_LVGL_V7") and GetDepend("DISABLE_LVGL_V9"):
    src = src + Glob('./lvgl_v8/*.c')
elif GetDepend("DISABLE_LVGL_V7") and GetDepend("DISABLE_LVGL_V8"):
    src = src + Glob('./lvgl_v9/*.c')

# add group to IDE project
objs = DefineGroup('app_fwk', src, depend = ['GUI_APP_FRAMEWORK'], CPPPATH = inc)
Return('objs')
