from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['BSP_USING_GC032A', 'BSP_USING_RTTHREAD'], CPPPATH = CPPPATH)

Return('group')
