Import('RTT_ROOT')
Import('rtconfig')
import os
import sys
from building import * 

cwd = GetCurrentDir()

src = []
path = [cwd]

src += ['air_mouse.c']
    
group = DefineGroup('Algorithm', src, depend = ['BSP_USING_AIR_MOUSE'], CPPPATH = path)

Return('group')
