CONFIG_RT_MAIN_THREAD_STACK_SIZE=4096
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_USING_ISR_LOG=y
CONFIG_ULOG_OUTPUT_THREAD_NAME=y
CONFIG_BSP_USING_FULL_ASSERT=y

# ==== Bluetooth ====
CONFIG_BLUETOOTH=y
CONFIG_BSP_BLE_SERIAL_TRANSMISSION=y
CONFIG_BT_CON_NUM_CUSTOMIZE=y
CONFIG_CFG_MAX_BT_ACL_NUM=2

# ==== DFU V2 ====
CONFIG_USING_DFU_V2=y
CONFIG_DFU_V2_USE_HOST_MODE=y
CONFIG_DFU_V2_USE_BLE_TRANSPORT=y
CONFIG_OTA_55X=y
# ==== Dependencies ====
CONFIG_PKG_USING_FLASHDB=y
CONFIG_PKG_FLASHDB_ERASE_GRAN=4096
CONFIG_PKG_SIFLI_MBEDTLS_BOOT=y

# ==== UI (optional, enable if screen available) ====
# CONFIG_PKG_USING_LITTLEVGL2RTT=y
# CONFIG_LVGL_V9=y
# CONFIG_LV_FONT_TINY_TTF_UBUNTU=y
# CONFIG_LV_USE_TINY_TTF=y
