CONFIG_LXT_DISABLE=y
CONFIG_BSP_USING_ADC=y
CONFIG_BSP_ENABLE_AUD_PRC=y
CONFIG_BSP_AUDPRC_TX0_DMA=y
CONFIG_BSP_AUDPRC_RX0_DMA=y
CONFIG_BSP_ENABLE_AUD_CODEC=y
CONFIG_BSP_USING_EPIC=y
CONFIG_BSP_USING_GPIO=y
CONFIG_BSP_USING_I2C=y
CONFIG_BSP_USING_I2C1=y
CONFIG_BSP_USING_LCPU_PATCH=y
CONFIG_BSP_ENABLE_MPI3=y
CONFIG_BSP_MPI3_MODE_1=y
CONFIG_BSP_QSPI3_MEM_SIZE=128
CONFIG_BSP_USING_PINMUX=y
CONFIG_BSP_USING_PWM=y
CONFIG_BSP_USING_PWM1=y
CONFIG_BSP_USING_PWMA1=y
CONFIG_BSP_USING_ONCHIP_RTC=y
CONFIG_BSP_USING_SPI=y
CONFIG_BSP_USING_TIM=y
CONFIG_BSP_USING_BTIM1=y
CONFIG_BSP_USING_LPTIM1=y
CONFIG_BSP_USING_UART=y
CONFIG_BSP_USING_UART1=y
CONFIG_BSP_UART1_RX_USING_DMA=y
CONFIG_BSP_USING_LCD=y
CONFIG_LCD_USING_TFT_CO5300=y
CONFIG_BSP_USING_TOUCHD=y
CONFIG_BSP_USING_KEY1=y
CONFIG_BSP_KEY1_PIN=34
CONFIG_BSP_KEY1_ACTIVE_HIGH=y
CONFIG_BSP_USING_LED1=y
CONFIG_BSP_LED1_PIN=25
CONFIG_BSP_LED1_ACTIVE_HIGH=y
CONFIG_PA_USING_AW8155=y
CONFIG_AW8155_GPIO_PIN=10
CONFIG_RT_USING_MTD_NOR=y
CONFIG_USING_ADC_BUTTON=y
CONFIG_ADC_BUTTON_GROUP_NUM=1
CONFIG_ADC_BUTTON_ADC_DEV_NAME="bat1"
CONFIG_ADC_BUTTON_GROUP1_MAX_NUM=3
CONFIG_ADC_BUTTON_GROUP1_ADC_DEV_CHANNEL=6
CONFIG_ADC_BUTTON_GROUP1_BUTTON1_VOLT=2973
CONFIG_ADC_BUTTON_GROUP1_BUTTON1_RANGE=190
CONFIG_ADC_BUTTON_GROUP1_BUTTON2_VOLT=2578
CONFIG_ADC_BUTTON_GROUP1_BUTTON2_RANGE=190
CONFIG_ADC_BUTTON_GROUP1_BUTTON3_VOLT=2185
CONFIG_ADC_BUTTON_GROUP1_BUTTON3_RANGE=190