Import('RTT_ROOT')
Import('rtconfig')
import os
import sys
from building import * 

cwd = GetCurrentDir()

src = []
path = [cwd]
src = Glob('*.cc') + Glob('*.c')
    
group = DefineGroup('WebRTC_VAD', src, depend = ['BSP_USING_WEBRTC_VAD'], CPPPATH = path)

Return('group')
