# CONFIG_UART_PORT1 is not set
# CONFIG_HCI_ON_FLASH is not set
# CONFIG_HCI_ON_LOG is not set
CONFIG_HCI_ON_LOG=y
CONFIG_LOG_ON_CONSOLE=y
CONFIG_LXT_DISABLE=y
CONFIG_BSP_ENABLE_AUD_PRC=y
CONFIG_BSP_AUDPRC_TX0_DMA=y
CONFIG_BSP_AUDPRC_RX0_DMA=y
CONFIG_BSP_ENABLE_AUD_CODEC=y