from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['BSP_USING_OV2640'], CPPPATH = CPPPATH)

Return('group')
