/* AUTO-GENERATED by fonts/SConscript -- do not edit. */
#include "lvgl/lvgl.h"
#ifdef LV_USING_FREETYPE_ENGINE
#include "app_module.h"
#include "lvsf_ft_reg.h"

static const char tiny55_full_name[] = "tiny55_full";
const lv_font_freetype_lib_dsc_t tiny55_full_lib = {
    .font_lib_size = 0,                          /* 0 -> file mode */
    .font_lib_data = "/assets/fonts/tiny55_full.ttf",
    .font_lib_name = tiny55_full_name,
};

LVSF_FREETYPE_FONT_REGISTER(tiny55_full)

#endif
