/* AUTO-GENERATED by fonts/SConscript -- do not edit. */
#include "lvgl/lvgl.h"
#ifdef LV_USING_FREETYPE_ENGINE
#include <stdbool.h>
#include <fcntl.h>
#include "dfs_posix.h"
#include "app_module.h"
#include "lvsf_ft_reg.h"

static const char tiny55_full_name[] = "tiny55_full";
const lv_font_freetype_lib_dsc_t tiny55_full_lib = {
    .font_lib_size = 0,                          /* 0 -> file mode */
    .font_lib_data = "/assets/fonts/tiny55_full.ttf",
    .font_lib_name = tiny55_full_name,
};

LVSF_FREETYPE_FONT_REGISTER(tiny55_full)

/* Weak hook consumed by littlevgl2rtt.c::gui_freetype_init. lvsf_font_inital
   asserts on FT_New_Face failure (closed-source lib), so if the .ttf isn't
   on the FS yet (first-boot before OTA file sync, FS corrupt, ...) the watch
   bricks. We probe with open()/close() (RT-Thread DFS POSIX layer doesn't
   define F_OK for access(), and SDK's own ft_fopen does the same dance) and
   return false to skip lvsf init; the UI then falls back to the LVGL
   built-in fonts (lv_font_montserrat_*).

   __attribute__((used)) is required because the only references to this
   function are weak externs in middleware. Without `used`, the ARM linker
   dead-strips the symbol — the weak extern resolves to NULL, the safety
   check is bypassed, and the watch bricks anyway. Verified by grepping
   main.htm: pre-`used`, the symbol is missing from the linked image. */
#ifdef _MSC_VER
bool is_freetype_safe_to_init(void)
#else
__attribute__((used)) bool is_freetype_safe_to_init(void)
#endif
{
    int fd = open("/assets/fonts/tiny55_full.ttf", O_RDONLY);
    if (fd < 0)
        return false;
    close(fd);
    return true;
}

#endif
