import os
from building import *

cwd = GetCurrentDir()
objs = []
entries = os.listdir(cwd)

Import('SIFLI_SDK')
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))
objs.extend(SConscript(cwd + '/../src/SConscript', variant_dir="src", duplicate=0))

Return('objs')
