Import('RTT_ROOT')
Import('rtconfig')
import os
import sys
from building import * 

cwd = GetCurrentDir()

src = []
path = [cwd]

src += ['gesture_detect.c']
    
group = DefineGroup('Algorithm', src, depend = ['BSP_USING_GESTURE_DETECT'], CPPPATH = path)

Return('group')
