from building import *

cwd        = GetCurrentDir()
src        = Glob('*.c')
CPPPATH    = [cwd]

# only enable POSIX.1b-1993 Real-time extensions
CPPDEFINES = ['_POSIX_C_SOURCE=199309L']

group = DefineGroup('POSIX', src, depend = ['RT_USING_PTHREADS'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
