/*
 * SPDX-FileCopyrightText: 2019-2025 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __BF0_HAL_RCC_SF32LB57_H
#define __BF0_HAL_RCC_SF32LB57_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __BF0_HAL_RCC_H
#error "Not include this file directly, include bf0_hal_rcc.h"
#endif /* __BF0_HAL_RCC_H */

typedef enum
{
    RCC_MOD_INVALID    = UINT32_MAX,
    RCC_MOD_DMAC1      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_DMAC1_Pos),
    RCC_MOD_MAILBOX1   = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_MAILBOX1_Pos),
    RCC_MOD_PINMUX1    = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_PINMUX1_Pos),
    RCC_MOD_USART2     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_USART2_Pos),
    RCC_MOD_EZIP       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_EZIP1_Pos),
    RCC_MOD_EPIC       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_EPIC_Pos),
    RCC_MOD_LCDC1      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_LCDC1_Pos),
    RCC_MOD_I2S1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_I2S1_Pos),
    RCC_MOD_I2S2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_I2S2_Pos),
    RCC_MOD_SYSCFG1    = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_SYSCFG1_Pos),
    RCC_MOD_EFUSEC     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_EFUSEC_Pos),
    RCC_MOD_AES        = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_AES_Pos),
    RCC_MOD_CRC1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_CRC1_Pos),
    RCC_MOD_TRNG       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_TRNG_Pos),
    RCC_MOD_GPTIM1     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_GPTIM1_Pos),
    RCC_MOD_GPTIM2     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_GPTIM2_Pos),
    RCC_MOD_BTIM1      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_BTIM1_Pos),
    RCC_MOD_BTIM2      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_BTIM2_Pos),
    RCC_MOD_PWM1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_PWM1_Pos),
    RCC_MOD_SPI1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_SPI1_Pos),
    RCC_MOD_SPI2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_SPI2_Pos),
    RCC_MOD_SECU1      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_SECU1_Pos),
    RCC_MOD_PDM1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_PDM1_Pos),
    RCC_MOD_PDM2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_PDM2_Pos),
    RCC_MOD_I2C1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_I2C1_Pos),
    RCC_MOD_I2C2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_I2C2_Pos),
    RCC_MOD_PTM1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 0, HPSYS_RCC_ENR1_PTM1_Pos),

    RCC_MOD_GPIO1      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_GPIO1_Pos),
    RCC_MOD_MPI1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_MPI1_Pos),
    RCC_MOD_MPI2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_MPI2_Pos),
    RCC_MOD_MPI3       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_MPI3_Pos),
    RCC_MOD_SDMMC1     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_SDMMC1_Pos),
    RCC_MOD_SDMMC2     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_SDMMC2_Pos),
    RCC_MOD_USBC       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_USBC_Pos),
    RCC_MOD_I2C3       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_I2C3_Pos),
    RCC_MOD_ATIM1      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_ATIM1_Pos),
    RCC_MOD_ATIM2      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_ATIM2_Pos),
    RCC_MOD_USART3     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_USART3_Pos),
    RCC_MOD_DCMI       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_DCMI_Pos),
    RCC_MOD_CAN1       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_CAN1_Pos),
    RCC_MOD_CAN2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_CAN2_Pos),
    RCC_MOD_AUDCODEC   = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_AUDCODEC_Pos),
    RCC_MOD_AUDPRC     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_AUDPRC_Pos),
    RCC_MOD_GPADC      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_GPADC_Pos),
    RCC_MOD_TSEN       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_TSEN_Pos),
    RCC_MOD_JPEGD      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_JPEGD_Pos),
    RCC_MOD_I2C4       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_HPSYS, 1, HPSYS_RCC_ENR2_I2C4_Pos),


    RCC_MOD_DMAC2      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_DMAC2_Pos),
    RCC_MOD_MAILBOX2   = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_MAILBOX2_Pos),
    RCC_MOD_PINMUX2    = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_PINMUX2_Pos),
    RCC_MOD_PATCH      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_PATCH_Pos),
    RCC_MOD_USART4     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_USART4_Pos),
    RCC_MOD_USART5     = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_USART5_Pos),
    RCC_MOD_SECU2      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_SECU2_Pos),
    RCC_MOD_PTC2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_PTC2_Pos),
    RCC_MOD_BTIM3      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_BTIM3_Pos),
    RCC_MOD_BTIM4      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_BTIM4_Pos),
    RCC_MOD_SYSCFG2    = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_SYSCFG2_Pos),
    RCC_MOD_GPIO2      = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_GPIO2_Pos),
    RCC_MOD_RFC        = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_RFC_Pos),
    RCC_MOD_PHY        = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_PHY_Pos),
    RCC_MOD_MAC        = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_MAC_Pos),
    RCC_MOD_CRC2       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_LPSYS, 0, LPSYS_RCC_ENR1_CRC2_Pos),

    RCC_MOD_ACPU       = RCC_MAKE_MOD_TYPE(RCC_MOD_TYPE_SECU1, 0, SECU1_ACPU_ENR_Pos),
} RCC_MODULE_TYPE;

typedef enum
{
    HPSYS_DVFS_MODE_D0,
    HPSYS_DVFS_MODE_D1,
    HPSYS_DVFS_MODE_S0,
    HPSYS_DVFS_MODE_S1,
    HPSYS_DVFS_MODE_NUM,
} HPSYS_DvfsModeTypeDef;

typedef enum
{
    LPSYS_DVFS_MODE_D,
    LPSYS_DVFS_MODE_S,
    LPSYS_DVFS_MODE_NUM,
} LPSYS_DvfsModeTypeDef;


#ifdef __cplusplus
}
#endif

#endif /* __BF0_HAL_RCC_SF32LB57_H */