from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB58_CORE_A128R32N1'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB58_CORE_A128R32N1'):
    group = group + SConscript('../sf32lb58-core_base/SConscript.base')

Return('group')
