[COMMON]
BAUND=2
RESET_SEL=0
ERASE_ALL=0

[DEVICE]
DEV_NUM=11
DEV_SEL=4
DEV_0=SF32LB55X_NOR
DEV_1=SF32LB55X_SD
DEV_2=SF32LB56X_NOR
DEV_3=SF32LB56X_NAND
DEV_4=SF32LB56X_SD
DEV_5=SF32LB52X_NOR
DEV_6=SF32LB52X_NAND
DEV_7=SF32LB52X_SD
DEV_8=SF32LB58X_NOR
DEV_9=SF32LB58X_NAND
DEV_10=SF32LB58X_SD

[SF32LB55X_NOR]
DRIVER=ram_patch.bin
FLASH1_ADDR=10000000
FLASH1_SIZE=4
FLASH1_SEL=1
FLASH2_ADDR=64000000
FLASH2_SIZE=32
FLASH2_SEL=1

[SF32LB55X_SD]
DRIVER=ram_patch_SD.bin
FLASH1_ADDR=10000000
FLASH1_SIZE=4
FLASH1_SEL=1
FLASH2_ADDR=64000000
FLASH2_SIZE=32
FLASH2_SEL=0
FLASH6_ADDR=68000000
FLASH6_SIZE=4096
FLASH6_SEL=1

[SF32LB56X_NOR]
DRIVER=ram_patch_56X.bin
FLASH2_ADDR=14000000
FLASH2_SIZE=16
FLASH2_SEL=1
FLASH5_ADDR=1C000000
FLASH5_SIZE=1
FLASH5_SEL=1

[SF32LB56X_NAND]
DRIVER=ram_patch_56X_NAND.bin
FLASH2_ADDR=64000000
FLASH2_SIZE=128
FLASH2_SEL=1
FLASH5_ADDR=1C000000
FLASH5_SIZE=1
FLASH5_SEL=1

[SF32LB56X_SD]
DRIVER=ram_patch_56X_SD.bin
FLASH2_ADDR=14000000
FLASH2_SIZE=16
FLASH2_SEL=0
FLASH5_ADDR=1C000000
FLASH5_SIZE=1
FLASH5_SEL=1
FLASH6_ADDR=A0000000
FLASH6_SIZE=8192
FLASH6_SEL=1

[SF32LB52X_NOR]
DRIVER=ram_patch_52X.bin
FLASH1_ADDR=10000000
FLASH1_SIZE=0
FLASH1_SEL=0
FLASH2_ADDR=12000000
FLASH2_SIZE=16
FLASH2_SEL=1

[SF32LB52X_NAND]
DRIVER=ram_patch_52X_NAND.bin
FLASH1_ADDR=10000000
FLASH1_SIZE=0
FLASH1_SEL=1
FLASH2_ADDR=62000000
FLASH2_SIZE=128
FLASH2_SEL=1

[SF32LB52X_SD]
DRIVER=ram_patch_52X_SD.bin
FLASH1_ADDR=10000000
FLASH1_SIZE=1
FLASH1_SEL=0
FLASH2_ADDR=12000000
FLASH2_SIZE=16
FLASH2_SEL=0
FLASH6_ADDR=a0000000
FLASH6_SIZE=59000
FLASH6_SEL=1

[SF32LB58X_NOR]
DRIVER=ram_patch_58X.bin
FLASH3_ADDR=14000000
FLASH3_SIZE=32
FLASH3_SEL=0
FLASH4_ADDR=18000000
FLASH4_SIZE=32
FLASH4_SEL=1
FLASH5_ADDR=1C000000
FLASH5_SIZE=1
FLASH5_SEL=1

[SF32LB58X_NAND]
DRIVER=ram_patch_58X_NAND.bin
FLASH3_ADDR=64000000
FLASH3_SIZE=32
FLASH3_SEL=0
FLASH4_ADDR=68000000
FLASH4_SIZE=128
FLASH4_SEL=1
FLASH5_ADDR=1C000000
FLASH5_SIZE=1
FLASH5_SEL=1

[SF32LB58X_SD]
DRIVER=ram_patch_58X_SD.bin
FLASH3_ADDR=14000000
FLASH3_SIZE=32
FLASH3_SEL=0
FLASH4_ADDR=18000000
FLASH4_SIZE=32
FLASH4_SEL=0
FLASH5_ADDR=1C000000
FLASH5_SIZE=1
FLASH5_SEL=1
FLASH6_ADDR=68000000
FLASH6_SIZE=4096
FLASH6_SEL=1

[BLE_SET]
BLE_SEL=0
BLE_RAN=0
BLE_UP=16
BLE_CUR_ADDR=C81100000001
BLE_MIN_ADDR0=01
BLE_MIN_ADDR1=00
BLE_MIN_ADDR2=00
BLE_MIN_ADDR3=00
BLE_MIN_ADDR4=11
BLE_MIN_ADDR5=C8
BLE_MAX_ADDR0=00
BLE_MAX_ADDR1=10
BLE_MAX_ADDR2=00
BLE_MAX_ADDR3=00
BLE_MAX_ADDR4=11
BLE_MAX_ADDR5=C8

[SN_SET]
SN_SEL=0
SN_RAN=0
SN_DES=LB55X
SN_UP=16
SN_CUR_VALUE=00000001
SN_MIN_VALUE=00000001
SN_MAX_VALUE=00010000

[CRYSTAL_CAL]
CRYSTAL_SEL=0
CRYSTAL_PORT=2
CRYSTAL_TOLERANCE=5
CRYSTAL_TIME=20
FIXVALUE_SEL=0
CRYSTAL_VALUE=0x1EA
CRYSTAL_TYPE=0
CRYSTAL_FREQ=3

[BATTERY_CALI]
BATTERY_SEL=0
BATTERY_VOLT_REF=4000
BATTERY_VOLT_RANGE=400
BATTERY_TOLERANCE=20
BATTERY_R_BIG=1000
BATTERY_R_SMALL=220

[SECFW_SET]
SECFW_SEL=0

[FLASH_SET]
FLASH_NUM=6
FLASH_SEL_0=0
FLASH_SEL_1=0
FLASH_SEL_2=0
FLASH_SEL_3=0
FLASH_SEL_4=0
FLASH_SEL_5=0
FLASH_ADDR_0=
FLASH_ADDR_1=64000000
FLASH_ADDR_2=
FLASH_ADDR_3=
FLASH_ADDR_4=1C000000
FLASH_ADDR_5=6A000000
FLASH_SIZE_0=
FLASH_SIZE_1=512
FLASH_SIZE_2=
FLASH_SIZE_3=
FLASH_SIZE_4=1
FLASH_SIZE_5=4096

;FILE_SEARCH type
;1)nothing:  will not search in map file, use FILE_ADDR
;2)readfile:  will read the addr from the bin file
;3)muti>string1||string2:  will search muti string in map
;4)string:  will search string in map
;The first bin must select FTABLE
[FILE_SET]
PACK_PATH=C:\Users\guich\Desktop\img\aidu
FACTORY_ADDR=0x1000E000
FILE_NUM=16

FILE_SEL_0=1
FILE_DES_0=FTABLE
FILE_NAME_0=ftab_qspi1_sec.bin||ftab.bin
FILE_ADDR_0=
FILE_SEARCH_0=readfile
;readfile will read the addr from the bin file
FILE_PATH_0=

FILE_SEL_1=1
FILE_DES_1=OTA MANAGER
FILE_NAME_1=bf0_ap.bin||ota_manager.bin
FILE_ADDR_1=
FILE_SEARCH_1=readfile
;readfile will read the addr from the bin file
FILE_PATH_1=

FILE_SEL_2=1
FILE_DES_2=APP
FILE_NAME_2=ER_IROM1.bin
FILE_ADDR_2=
FILE_SEARCH_2=muti>Load Region LR_IROM1 (Base:||Load Region LR_XIP_LRBIN (Base:
;muti Load Region LR_IROM1 (Base: or Load Region LR_IROM1 (Base:
FILE_PATH_2=

FILE_SEL_3=1
FILE_DES_3=PIC
FILE_NAME_3=ER_IROM2.bin
FILE_ADDR_3=
FILE_SEARCH_3=Load Region LR_IROM2 (Base:
FILE_PATH_3=

FILE_SEL_4=1
FILE_DES_4=FONT
FILE_NAME_4=ER_IROM3.bin
FILE_ADDR_4=
FILE_SEARCH_4=Load Region LR_IROM3 (Base:
FILE_PATH_4=

FILE_SEL_5=1
FILE_DES_5=TINY FONT
FILE_NAME_5=ER_IROM3_TINY.bin
FILE_ADDR_5=
FILE_SEARCH_5=Load Region LR_IROM3_TINY (Base:
FILE_PATH_5=

FILE_SEL_6=1
FILE_DES_6=OTA PIC
FILE_NAME_6=ER_IROM4.bin
FILE_ADDR_6=
FILE_SEARCH_6=Load Region LR_IROM4 (Base:
FILE_PATH_6=

FILE_SEL_7=1
FILE_DES_7=FS ROOT
FILE_NAME_7=root.bin
FILE_ADDR_7=
FILE_SEARCH_7=Load Region LR_FS_ROOT (Base:
FILE_PATH_7=

FILE_SEL_8=1
FILE_DES_8=FS EX
FILE_NAME_8=ex.bin
FILE_ADDR_8=
FILE_SEARCH_8=Load Region LR_FS_EX (Base:
FILE_PATH_8=

FILE_SEL_9=1
FILE_DES_9=FS SYS
FILE_NAME_9=sys.bin
FILE_ADDR_9=
FILE_SEARCH_9=Load Region LR_NVM_SYS (Base:
FILE_PATH_9=

FILE_SEL_10=1
FILE_DES_10=BOOT
FILE_NAME_10=bootloader.bin
FILE_ADDR_10=
FILE_SEARCH_10=readfile
FILE_PATH_10=

FILE_SEL_11=1
FILE_DES_11=LCPU
FILE_NAME_11=lcpu_flash.bin
FILE_ADDR_11=
FILE_SEARCH_11=
FILE_PATH_11=

FILE_SEL_12=1
FILE_DES_12=LCPU_PATCH
FILE_NAME_12=lcpu_rom_patch.bin
FILE_ADDR_12=
FILE_SEARCH_12=
FILE_PATH_12=

FILE_SEL_13=1
FILE_DES_13=FONT
FILE_NAME_13=font.bin
FILE_ADDR_13=
FILE_SEARCH_13=Load Region LR_FS_FONT (Base:
FILE_PATH_13=

FILE_SEL_14=1
FILE_DES_14=IMAGES
FILE_NAME_14=images.bin
FILE_ADDR_14=
FILE_SEARCH_14=Load Region LR_FS_IMAGES (Base:
FILE_PATH_14=

FILE_SEL_15=1
FILE_DES_15=WATCH
FILE_NAME_15=watch.bin
FILE_ADDR_15=
FILE_SEARCH_15=Load Region LR_FS_WATCHFACE (Base:
FILE_PATH_15=


