# for module compiling
import os
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
list = os.listdir(cwd)

src = Glob('*.c')
objs = DefineGroup('wifi', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
