from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_DPI_HDK_LB575YBBN6_N16_EPD'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_DPI_HDK_LB575YBBN6_N16_EPD'):
    group = group + SConscript('../sf32lb57-dpi-hdk_base/SConscript.base')

Return('group')
