CONFIG_BSP_USING_PDM=y
CONFIG_BSP_USING_PDM1=y
CONFIG_BSP_USING_PDM2=y
CONFIG_BSP_UART1_TX_USING_DMA=y
# CONFIG_BSP_USING_LCD is not set
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_USING_ULOG=y
CONFIG_RT_USING_MEMTRACE=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_USING_ACPU_CTRL_FWK=y
CONFIG_AUDIO=y
CONFIG_AUDIO_LOCAL_MUSIC=y
CONFIG_AUDIO_RX_USING_PDM=y
CONFIG_PKG_USING_ANYKA=y
CONFIG_ANYKA_TWO_MIC=y
CONFIG_ANYKA_RUN_IN_ACPU=y
CONFIG_USING_ELM_RW=y
CONFIG_PKG_LIB_OPUS=y
CONFIG_STARTUP_STACK_SIZE=32000
CONFIG_STARTUP_HEAP_SIZE=200000
