CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_USING_IPC_QUEUE=y
CONFIG_USING_ACPU_CTRL_FWK=y
CONFIG_PKG_LIB_OPUS=y
CONFIG_RT_MAIN_THREAD_STACK_SIZE=20480
CONFIG_STARTUP_STACK_SIZE=4096
CONFIG_STARTUP_HEAP_SIZE=4096
