# for module compiling
import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]
group = DefineGroup('Drivers', src, depend = ['HR_USING_GH3018'], CPPPATH = path, LIBPATH = path)
Return('group')
